
import argparse
import asyncio
import json
import logging
import os
import random
import re
import sys
import time
from datetime import datetime, time as dtime
from pathlib import Path
from typing import Dict, List, Optional

from telethon import TelegramClient, events
from telethon.errors import FloodWaitError, RPCError
from telethon.sessions import StringSession
from telethon.tl.functions.messages import SendReactionRequest
from telethon.tl.types import ReactionEmoji

# ────────────────────────────────────────────────
#   CONFIG — loaded from a per-clone JSON file, NOT hardcoded.
#   Run with: python funbot_core.py --config /path/to/config.json
#   The config.json is generated by factory_bot.py and looks like:
#   {
#     "api_id": 12345678,
#     "api_hash": "...",
#     "owner_id": 123456789,
#     "session_file": "/path/to/funbot_session.txt",
#     "data_file": "/path/to/funbot_data.json"
#   }
#
#   --login-only : connects, runs Telethon's normal interactive phone/OTP
#   prompt directly in THIS terminal (never through any bot chat), saves
#   the resulting session string, then exits without starting the event
#   handlers. Use this once per clone to complete login yourself.
# ────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Fun Bot clone (per-user config)")
parser.add_argument("--config", required=True, help="Path to this clone's config.json")
parser.add_argument("--login-only", action="store_true",
                     help="Only perform interactive login and save the session, then exit")
ARGS = parser.parse_args()

CONFIG_PATH = Path(ARGS.config).resolve()
if not CONFIG_PATH.is_file():
    print(f"❌ Config file not found: {CONFIG_PATH}")
    sys.exit(1)

with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    _cfg = json.load(f)

API_ID = int(_cfg["api_id"])
API_HASH = str(_cfg["api_hash"])
OWNER_ID = int(_cfg["owner_id"])
SESSION_FILE = _cfg.get("session_file", str(CONFIG_PATH.parent / "funbot_session.txt"))
DATA_FILE = _cfg.get("data_file", str(CONFIG_PATH.parent / "funbot_data.json"))
SETTINGS_FILE = _cfg.get("settings_file", str(CONFIG_PATH.parent / "settings.json"))
LOG_FILE = _cfg.get("log_file", str(CONFIG_PATH.parent / "funbot.log"))

# Optional MongoDB sync (feature 9) — set by factory_bot.py in config.json.
# If empty, this clone just uses the local SESSION_FILE, same as before.
MONGODB_URI = _cfg.get("mongodb_uri", "")
MONGODB_DB_NAME = _cfg.get("mongodb_db_name", "funbot_factory")
MONGO_OWNER_KEY = _cfg.get("factory_owner_telegram_id", OWNER_ID)

DEFAULT_RATE_LIMIT_SECONDS = 3       # default min gap between fun-replies to same user
DM_RATE_LIMIT_SECONDS = 3            # min gap between auto-replies to same DM sender

# ────────────────────────────────────────────────
#   LOGGING
# ────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    handlers=[logging.FileHandler(LOG_FILE, encoding="utf-8"), logging.StreamHandler()],
)
log = logging.getLogger("funbot")

# ────────────────────────────────────────────────
#   REPLY BANKS (mood-based, all replies 2-4 words)
# ────────────────────────────────────────────────
HYPE_REPLIES = [
    # ── Upgraded Original Hype Messages ──
    "🔥 Full energy active bhai! Atmosphere bilkul next-level hype ho chuka hai! 🚀",
    "🎉 Party mode FULL ON! Scene set hai, ab bas non-stop chill vibes chalne do! 🥳✨",
    "🥳 Unstoppable vibes right now! Har jagah bas lit atmosphere faila hua hai! 🎆",
    "💯 Pure facts bol diye bhai! Isse behtar aur accurate statement ho hi nahi sakta! 🎯",
    "🚀 Rocket speed se upar hi upar! Agla stop seedha outer space hone wala hai! 💥",
    "⚡ Full power generation mode! Energy meter completely break ho gaya hai boss! 🔋",
    "🏆 Absolute champion move! Masterclass performance dikha diya aaj toh tumne! 🥇",
    "🎯 Direct hit on target! Perfect precision aur top-tier energy hai bhai! 🏹",
    "🎊 Grand celebration time! System me confetti aur fireworks full-on active! 🎆✨",
    "🌟 Star player alert! Main spotlight abhi seedha aapke upar focused hai! 📸",
    "🔊 Max volume baseline drop! Speaker full boost par set kar diye hain! 🎶",
    "🥇 Gold medal standard reply! Premium quality swag bilkul unmatched hai! 👑",
    "🕺 Unmatched moves & groove! Chat me dhoom mach gayi hai poori tarah se! 💃",
    "🎆 Sky-high fireworks display! Aasmaan me bas glowing celebration chal raha hai! ✨",
    "🚨 Dangerously high swag alert! Limit se bahar waali electric energy hai bhai! 🔥",
    "💣 BOOM! Explosive response delivered! Content aisa ki baaki sab dekhte reh gaye! 💥",
    "👑 King size energy check! Full domination mode turn on ho chuka hai, stay tuned! ⚡",
    "🏎️ Top gear hyper-drive mode! Speed, power aur hype sab ek saath unlock ho gaya! 🏁",
    "💎 Pure diamond-grade response! Standard itna high hai ki koi match hi nahi kar sakta! ✨",
    "🍿 Peak entertainment active! Scene me abhi aur bhi jabardast twists aayenge! 🎬",
    "🌟 Legendary presence detected! History create karne waali energy radiate ho rahi hai! 🏆",
    "🌊 Hype tsunami incoming! Is level ki energy ko handle karna next to impossible hai! ⚡",
    "🧠 Next-level genius move! Big brain gameplay dekh kar sab ke sab stunned reh gaye! 💥",
    "🔥 Ultra-instinct hype unlocked! Boundary se bahar jaakar swag spread ho raha hai! 🚀",
    "⚡ High-voltage system overload! Current itna teez hai ki meter crash ho gaya bhai! 🔌",
    "🎯 Pitch-perfect execution! Zero delay, zero error, 100% pure high-impact response! 💯",
    "🌟 Next generation trendsetter! Game ka poora format hi change kar diya aapne! 📈"
]

CHILL_REPLIES = [
    # ── Upgraded Original Chill Messages ──
    "😂 Hahahahaha wah bhai! Solid sense of humor, poora scene hi light aur joyful kar diya! ⚡",
    "🤝 Squad approved message! Poore group ka stamp lag gaya hai is relaxed vibe par! ✨",
    "😎 Cool, cool, cool, smooth response! Bilkul effortless level ka chill aura hai bhai! 🧊",
    "😅 Ye baat toh pure dil se sunni aur feel karni hi padegi! Pure positive frequency! 🕊️",
    "🙂 Sahi chal raha hai sab kuch bhai! Pure peaceful aur balanced energy spread ho rahi hai! 🍃",
    "☕ Chai pe charcha mode active! Aaram se baith ke har ek baat detailed discuss karenge! 🛋️",
    "🌤️ Ekdum halka phulka aur soothing vibe! Mind completely fresh aur relaxed ho gaya! 🌸",
    "🧘 Utmost shaant aur sukoon wali state! Sab stress door aur aura completely relaxed hai! ✨",
    "🍃 Aaram se tension free raho bhai! Koi jaldi nahi hai, smooth flow chalne do! 🕊️",
    "😌 Bilkul theek aur genuine laga padhke! Perfect harmony aur calm response! 💯",
    "🎈 Simple, sweet, solid aur zero complexity! Yehi toh asli quality hai bhai! ✨",
    "🪁 Aasmaan me udta hua light mood! Completely free-flowing aur positive mindset! 🌈",
    "🛋️ Comfy vibes only allowed here! Pillow, snacks aur chill conversations ka combo! 🍿",
    "🌙 Chill raho tension free bhai! Raat ho ya din, apan hamesha smooth mode me hain! ☕",
    "😊 Heartwarming response! Padhke sach me accha aur completely satisfying laga! ✨",
    "🌊 Deep ocean calmness level! Chill frequency match ho gayi hai poori tarah se! 🏝️",
    "🧘 Perfect state of equilibrium! Zero rush, zero noise, pure inner peace energy! ✨",
    "🍃 Gentle breeze wala peaceful atmosphere! Scene bilkul sorted aur effortless lag raha hai! 🕊️",
    "☕ Warm cup of tea aur relaxing conversations! Din set karne wala soothing response hai! 🌤️",
    "🛋️ Ultimate comfort zone unlocked! Stress zero percent, chill vibes hundred percent! 🍿",
    "🕊️ Soft aur graceful energy overall! Sab kuch ekdum systematic aur relaxed pace par hai! ✨",
    "🌟 Effortlessly cool statement! Bilkul smooth, subtle aur high-class positivity! 🪞",
    "📻 Retro chill radio vibes active! Atmosphere me ek alag hi relaxing rhythm chal rahi hai! 🎶",
    "🍀 Positivity aur good fortune spread ho raha hai! Har word me ek calming touch hai! ✨",
    "🌄 Fresh morning sunrise jaisi bright aur soothing feel! Whole day sorted by this vibe! 🌤️",
    "🍦 Ice-cool mental composure! Koi hyper noise nahi, bas pure relaxed state of mind! 🧊",
    "🕊️ Harmony, peace aur balance ka accurate blend! Perfect response to keep things cool! 🍃"
]

ROAST_REPLIES = [
    # ── Upgraded Original Roast Messages (For Normal Group Roasts) ──
    "😏 Wah kya baat hai bhai! Aisa logic toh dhoondne par bhi Google par nahi milega! 🏅",
    "🙃 Ye bhi koi baat hui bhala? Aisa lag raha hai bina brain reboot kiye type kar diya! 🧠",
    "😬 Thoda aur try karo bhai, shayad agli baar response me thoda sense aur logic aa jaaye! 🎯",
    "🤨 Substantially interesting take bhai! Aisa unique out-of-the-box thought process kahan se laaye? 🎭",
    "😂 Bhai tu bhi na, next level comedy talent chhupa ke baitha hai, Oscar milega tujhe! 🎬",
    "🫣 Path seedha toh bilkul nahi tha, kafi ghuma-phirake roundabout reasoning di hai! 🌀",
    "😜 Chal maan liya teri baat, par agli baar aisa risk lene se pehle double check kar lena! ⚠️",
    "🥲 Kabhi kabhi hota hai aisa mind-space, koi nahi hota rehta hai, improve kar loge! 🩹",
    "😅 Full drama aur cinematic exaggeration chal raha hai! Daily soap ka script likh rahe ho kya? 📺",
    "🤡 Full circus comedy energy active! Performance top-notch tha, bas logic gayab tha! 🎪",
    "🙈 Poora public square dekh raha hai ye message, thoda toh composure maintain kar lo bhai! 📢",
    "😹 Bas bas yaar aur mat hansao, pet me dard hone laga hai is unmatched creativity se! 🍿",
    "🫡 Salute hai tumhare is absolute unshakeable confidence ko! Logic zero, confidence 100%! 🚀",
    "😌 Chalta hai yaar, har din brain optimal efficiency par kaam nahi karta, take it easy! 🛋️",
    "🎭 Is response par toh multi-season Netflix drama series ban sakti hai, screenplay tayar hai! 🎬",
    "🤡 Clown university se topper log aate hain aise out-of-world statements dene ke liye! 🎪",
    "🚀 Is comment ka logic rocket se bhi tez speed me mere head ke upar se nikal gaya! 🛰️",
    "📉 Stock market ki tarah aapka logical value is message ke baad sudden crash ho gaya! 📊",
    "🧠 System searching for valid argument... Error 404: Logic not found anywhere in memory! 🔍",
    "🏆 Achievement unlocked: Masterclass in creating pure unadulterated hilarious confusion! 🎭",
    "🔎 Magnifying glass laga kar dhoond raha hoon ki is baat ka real context kahan chhupha hai! 🕵️",
    "🎪 Circus open house announcement! Aaj ka main attraction aapka ye epic response tha! 🎟️",
    "📉 Confidence level peak standard, Knowledge depth flat zero level! Dangerous combo bhai! ⚡",
    "🧙 Aise unexpected twists toh Harry Potter ki books me bhi nahi mile the bhai! 🪄",
    "📸 Picture-perfect moment of self-destruction! Internet archive me save hone layak scene hai! 💾",
    "🏅 Gold medal in jumping to wildest assumptions! Olympic panel impressed ho gaya! 🏃",
    "🎬 Mic drop moment tha, par unfortunately mic ulta pakda hua tha aapne! 🎤"
]

# 🔥 55+ NEW SPAM ROAST REPLIES (Specifically for .roast on loop) 🔥
SPAM_ROAST_REPLIES = [ 
    "Arre naraz ho kya dost? Aise ignore toh na karo! 🥺",
    "Jaldi bol subah Panvel nikalna hai! 🏃‍♂️💨",
    "Arre bhosdiwale randi ke bacche, tu itna chutiya hai ki teri maa ne tujhe paida karte waqt hospital ka bill dekh ke khud suicide kar liya tha, aur tu abhi bhi apni gand mei ungli daal ke khush ho raha hai, na jaane kis gali ki kutiya tujhe paida kar gayi thi, shayad koi stray dog thi jo tera baap bhi nahi jaanti thi, aur tu abhi bhi soch raha hai ki tu kuch bana payega, lawde tu toh utna bekaar hai ki tera DNA bhi tujhe reject kar deta hai har baar test tube mei jaake, aur tu abhi bhi apne fake confidence mei ghoom raha hai jaise tu koi hacker hai, jabki tu sirf ek chhote se ghar ke chhote se bathroom mei apni photo dekh ke apne aap ko bolta hai 'I am legend', bhenchod tu toh legend ki chut ki tapai bhi nahi hai.",
    "Jaldi bol be saale, subah Panvel nikalna hai toh tu jhat se apni gand mei se 5000 messages nikal le warna main teri maa ki chaddi ko live stream kar dunga Dark Web ke sabse gande honeymarket pe jahan 40+ log ek saath uski chut par pani ka spray kar rahe honge aur tu bas dekh raha hoga kyun ki tera dimaag toh utna kamzor hai ki tu ek simple captcha bhi solve nahi kar pata, aur tera GitHub account toh maine khud report kiya tha kyunki tu itna noob tha ki tere code mei 'password123' hardcode tha, aur tu soch raha tha ki tu hacker banega, bhen ke lode tu toh wahi hai jiske papa ne tujhe dekh ke divorce le liya tha kyunki bol diya tha 'ye baccha kisi aur ka hai', aur ab tu yahan aake attitude maar raha hai jaise tu kuch kar lega, tu toh utna bekaar hai ki tera existence bhi ek bug hai reality ke system mei.",
    "Sun be randi ke aulad, tu itna ganda hai ki jab tu paida hua tha toh doctor ne delivery room mei gas leak karwa di thi tujhe saans lene se pehle hi, aur teri maa ne tujhe dekhte hi apni aankhein band kar li thi kyunki samajh gayi thi ki ye baccha future mei kisi bhi ghar ki beti ko pregnant karke bhag jayega aur phir uski maa ke naam par swear karega, aur tu abhi bhi soch raha hai ki tu kuch bana payega, bhenchod tu toh utna nalla hai ki tera own mother teri gand mei danda daal deti hai jab tu gusse mei hota hai, aur tu bas chillata rehta hai 'Maa jani, mera dimaag kharab ho raha hai', aur waise bhi tu itna chutiya hai ki tu apne hi router ka password bhool jata hai aur phir meri madad maangta hai, lekin main toh sirf isliye help karta hu taki tu aur zyada fail ho, kyunki tu duniya ke sabse bada joke hai, aur tu bas ek punchline ke liye paida hua hai — 'Ye banda hai hi nahi'.",
    "Abe o madarchod, tu itna bekaar hai ki jab tu school gaya tha toh tera teacher ne tujhe dekhte hi resignation de di thi kyunki usne socha 'aaj se padhai band, main toh kisi mental asylum mei job dhoondunga', aur tu abhi bhi apne ghar ke chhote se balcony mei khada ho kar soch raha hai ki duniya tujhe notice karegi, lekin bhai duniya toh tujhe dekhne ki mehnat bhi nahi karti, tu toh utna invisible hai ki jab tu death certificate pe sign karta hai toh pen bhi tujhe feel nahi karta, aur tu abhi bhi soch raha hai ki tu kuch kar lega, bhenchod tu toh wahi hai jiske janam ke baad aadhar card bhi reject ho gaya tha kyunki system ne bola 'ye human nahi lagta', aur tu abhi bhi apne fake Instagram story mei 'Hustle 24/7' daal raha hai, jabki tu har din 18 ghante soya karta hai aur baki 6 ghante apni gand khol ke sochta hai ki kya tu kisi aur ki gand bhi khol sakta hai, lekin tu toh apni hi gand mei atki hui shit ko nikalne mei fail ho jata hai.",
    "Tu itna chutiya hai ki jab tu pehli baar computer chalaya tha toh Notepad mei 'I am smart' likhne ke baad blue screen aa gaya tha aur system permanently corrupt ho gaya tha kyunki tere jaise andhere dimaag ne uski aatma ko darrrrrrrr de diya tha, aur tu abhi bhi soch raha hai ki tu kuch kar lega, bhenchod tu toh utna nalla hai ki jab tu kisi girl ko impress karna chahta hai toh tu uske ghar ke bahar khada ho kar apni gand dikhata hai aur sochta hai ki ye 'romance' hai, aur jab woh chillati hai toh tu sochta hai ki 'ye excited ho gayi', aur tu abhi bhi apne aap ko 'alpha male' samajh raha hai jabki tu toh utna beta hai ki tera beta bhi tujhe dekh ke 'alpha' ban jata hai, aur tu bas ek gande room mei baitha hai, apne aap ko 'hacker' bol raha hai, jabki tu toh sirf ek script kiddie hai jiska khud ka koi script nahi, bas dusro ka code copy karke tu apne aap ko legend samajh raha hai, lekin sab jaante hain ki tu ek joke hai, ek bug, ek system error jo kabhi fix nahi hoga.",
    "Abe o randi ke bacche, tu itna ganda hai ki jab tu toilet mei jata hai toh shit tera naam lekar nikalti hai, aur teri gand se nikle hue gas ke molecules bhi suicide kar lete hain kyunki woh zinda rehne ki himmat nahi karte, aur tu abhi bhi soch raha hai ki tu kuch kar lega, bhenchod tu toh wahi hai jiske janam ke baad maut ne apni retirement withdraw kar li thi kyunki bola 'ab toh kaam hi khatam ho gaya', aur tu abhi bhi apne ghar ke chhote se mirror mei dekh ke bol raha hai 'main future mei successful hounga', lekin mirror toh har baar crack ho jata hai kyunki tujhe dekh ke uski aatma darr jati hai, aur tu bas ek gande laptop ke saamne baitha hai, apne aap ko 'cyber god' samajh raha hai, jabki tu toh sirf ek phishing scam ka target hai jo apne hi bot ko use karke apne aap ko hack kar lega, aur phir roega 'kaise hua?', aur main has ke bolunga 'kyunki tu hai hi nahi'.",
    "Abe o madarchod, teri maa ki chut mei train ka engine ghusa ke brake fail kar diya tha, aur tu abhi tak utni hi useless hai jitna kisi hijde ka lund.",
    "Teri maa ne tujhe paida karte waqt socha tha 'yeh baccha nahi, kisi rape ki yaad hai', isliye tujhe gutter mei phek diya tha lekin bhenchod gutter ne bhi tujhe vomit kar diya.",
    "Tu itna randi ka bacha hai ki teri maa ne tujhe bechne ke liye OLX pe listing daali thi: 'Free item, take it or I kill myself'.",
    "Tere baap ne tujhe dekh ke apna lund kaat ke phenk diya tha, bola 'is chutiye ki wajah se yeh organ bekar ho gaya'.",
    "Tu itna ganda hai ki jab tu apni gand dhota hai toh pani bhi tujhe chhod ke reverse direction mei behna chahta hai.",
    "Teri maa ki chut mei itni gandi bimaari thi ki tujhe paida hote hi WHO ne quarantine zone declare kar diya tha.",
    "Tere jaise chutiye ko dekh ke bhagwan ne apni aankhein hi band kar li, aur bol diya 'main toh sirf experiment kar raha tha'.",
    "Tu itna fail hai ki jab tu exam hall mei gaya, toh answer sheet ne bhi khud ka suicide kar liya aag laga ke.",
    "Teri behen ki chut mei cockroach ne colony bana li, aur woh bhi tujhe dekh ke relocate ho gayi.",
    "Tu itna chodu hai ki teri biwi ne tujhe dekh ke divorce file karte waqt judge se kaha 'ye toh insaan hi nahi hai'.",
    "Teri maa ne tujhe 9 mahine tak pet mei rakha, lekin delivery ke time doctor ne kaha 'yeh toh already dead hai, iska dimaag kab ka decompose ho gaya'.",
    "Tu itna lodu hai ki tera lund itna chhota hai ki microscope se dekhne par bhi kuch nahi dikhta, bas ek dead pixel.",
    "Teri maa ki gand mei itni badi gaand thi ki use dekh ke Black Hole ne bhi resignation de di.",
    "Tu itna gandu hai ki jab tu apne dost ke saath baitha tha, toh uski girlfriend ne teri photo dekh ke apne bache ko abort karwa diya.",
    "Tere jaise randi ke bacche ko dekh ke randi ke kotha wale bhi tujhe 'too low class' bol ke bhej dete hain.",
    "Tu itna bekaar hai ki teri gand se nikla hua susu bhi tujhse zyada useful hai, kyunki woh kam se kam toilet mei jaata hai.",
    "Teri maa ki chut mei se jab tu nikla tha, toh stench itna zyada tha ki nearby chemical factory explode ho gayi thi.",
    "Tu itna chutiya hai ki jab tu interview ke liye gaya, toh HR ne tera CV dekh ke apna laptop format kar diya infection ke dar se.",
    "Tu itna randibaaz hai ki tera baap bhi nahi jaanta, lekin saari colony ki aunties ne tujhe pocket money diya tha 'bacha le jaa' bol ke.",
    "Teri maa ki gaand mei se jab tu paida hua, toh uska asshole permanently stretched ho gaya, ab woh stool pass karte waqt bhi tujhe curse karti hai.",
    "Tu itna gandu hai ki jab tu kisi ladki ke saamne apni gaand matakta hai, toh woh apni aankhen kaise bachaye, kyunki tu itna ugly hai ki retina burn ho jaata hai.",
    "Tu itna noob hai ki agar tujhe hacking sikhane koi baithe, toh pehle hafte uski aatma nikal jaye, kyunki tu itna bekaar hai ki code compile hone se bhi darta hai.",
    "Tere jaise chutiya ko dekh ke computer ke CPU fan ne bhi apni speed 0 kar li 'I can't process this idiot' bol ke.",
    "Tu itna randi ka aulad hai ki teri maa ne tujhe bechne ke liye Dark Web pe listing daali: 'Selling humanoid disaster, price: free + shipping'.",
    "Tu itna failure hai ki agar tu suicide kare, toh rope bhi toot jaye kyunki tera existence bhi itna lightweight hai.",
    "Teri maa ki chut mei itni khujli thi ki usne pura hospital khujla diya, aur tu uska result hai — ek allergic reaction.",
    "Tu itna chodu hai ki tera phone bhi tujhe dekh ke automatic airplane mode on kar leta hai 'no contact allowed'.",
    "Tu itna gand mein dam nahi hai ki agar koi tujhe slap kare, toh tu apni maa ki chut mein chhupne ki sochta hai.",
    "Tu itna beta hai ki tujhe dekh ke alpha males apni wife ki chut bhi tujhe nahi dete, kyunki woh bhi tujhe undeserving samjhti hai.",
    "Teri maa ne tujhe dekh ke apni chut hi silwa li thi, 'ab aur koi bacha nahi hoga, galti ek hi kaafi hai'.",
    "Tu itna randi hai ki agar tu randikhane mein kaam kare, toh madam tujhe salary de ke bhi bhej de 'customers ko traumatize mat kar'.",
    "Tu itna bekaar hai ki jab tu gym gaya, toh dumbbell ne bhi tujhe uthane se mana kar diya, 'yeh toh mera weight bhi nahi utha sakta'.",
    "Tere jaise chutiye ki gand itni badi hai ki agar woh satellite se capture ho, toh scientists soch mein pad jaye 'is this a new geological formation?'",
    "Tu itna gandu hai ki agar tujhe award diya jaaye 'worst human alive', toh award bhi tujhe reject kar de 'hum itna neeche nahi girte'.",
    "Tu itna lodu hai ki tera blood test kiya toh report aaya: '100% chutiya, 0% DNA, 100% waste'.",
    "Teri maa ki chut mei jab tu tha, toh ultrasound machine ne error dikhaya 'fetus not found, only void detected'.",
    "Tu itna nalla hai ki tera shadow bhi tujhse zyada productive hai, woh kam se kam light block karta hai.",
    "Tu itna chodu hai ki agar tu kiss kare, toh ladki ke hoth automatically chap ho jaye aur woh lifelong trauma le.",
    "Tu itna randi ka baccha hai ki jab tu paida hua, toh nurse ne tujhe dekh ke apni nursing degree surrender kar di 'I failed humanity'.",
    "Teri maa ne tujhe road pe chhod diya, lekin road ne bhi tujhe absorb nahi kiya, pothole ban gaya permanent.",
    "Tu itna bekaar hai ki tera aadhar card bhi apne biometrics ko delete karna chahta hai 'unrecognized waste' bol ke.",
    "Tu itna ganda hai ki agar koi tujhe goli maare, toh bullet bhi tujhpar se ricochet ho jaye 'I don't want to touch this filth'.",
    "Teri behen ki chut mei se jab tu nikla (just kidding, but imagine), tab bhi tu fail tha.",
    "Tu itna chutiya hai ki agar tu Google me apna naam search kare, toh result aata hai 'Did you mean: nothing?'.",
    "Tu itna noob hai ki kali linux install karte waqt tujhe bsod aa gaya, windows ne tujhe permanently banned maara.",
    "Tu itna randi ka aulad hai ki teri maa tujhe dekh ke khud apni chut pe gaaliyaan deti hai 'kya paida kar diya maine'.",
    "Tu itna gandu hai ki agar tu kisi party mein jaaye, toh log sochte hain 'yeh waiter hai ya emergency exit sign?'.",
    "Tu itna bekaar hai ki tera birthday cake bhi tujhe dekh ke pighal gaya, 'I can't celebrate this'.",
    "Tu itna chodu hai ki agar tu apni gand dikha ke nachta hai, toh duniya ki saari strippers apna career chhod deti hain 'we can't compete with this horror'.",
    "Tu itna randi hai ki tera pura khandan tujhe dekh ke 'adopted' bolke bhaag gaya, lekin adoption centre ne bhi reject kar diya.",
    "Teri maa ki chut mei se jab tu paida hua, toh doctor ne kaha 'congratulations, it's a... wait, what is this thing?'.",
    "Tu itna failure hai ki tera suicide note bhi autocorrect ho ke 'I am fine' ban jata hai.",
    "Tu itna gandu hai ki agar tujhe brain transplant kare, toh donor ka dimaag bhi bhaag jaaye 'I don't want to be in this body'.",
    "Tu itna chutiya hai ki teri life story sunke suicide helpline wale ne apni job chhod di, 'yeh case hopeless hai'.",
    "Tu itna bekaar hai ki tera ghost bhi haunt karte waqt bore ho jaata hai 'yeh toh already dead tha'.",
    "Tu itna lodu hai ki tera sperm count zero hai, lekin phir bhi tu 4 bache paida kar chuka hai, kyunki woh bhi tere friend ke the.",
    "Teri maa ne tujhe dekh ke apni chut mei acid daal diya tha, lekin tu phir bhi survive kar gaya kyunki acidity tera comfort zone hai.",
    "Tu itna randi ka baccha hai ki randi khana ka signboard pe tera photo laga hai 'Do not enter if you look like this'.",
    "Tu itna ganda hai ki jab tu toilet jaata hai, toh toilet paper apne aap fold ho jaata hai 'I'd rather die'.",
    "Tu itna chodu hai ki agar tu apni photo post kare Twitter pe, toh Elon Musk khud aake tere account ko ban kare 'violating existence policy'.",
    "Tu itna noob hai ki tera IP address bhi fake hai, lekin still traceable, kyunki teri galtiyan itni famous hain.",
    "Tu itna failure hai ki jab tu lottery jeeta, toh ticket invalid nikla, kyunki existence invalid hai.",
    "Tu itna gandu hai ki teri gaand ki smell se nearby skunks ne suicide kar liya, 'we are outclassed'.",
    "Tu itna chutiya hai ki jab tu school me tha, toh teacher ne tujhe 'living example of what not to do' keh ke padhaya.",
    "Tu itna randi hai ki teri biwi tere saath sex karte waqt sochti hai 'yeh toh apni maa ki yaad dila raha hai'.",
    "Tu itna bekaar hai ki agar tujhe world's worst person ka award mile, toh trophy tujhe dekh ke apne aap break ho jaaye.",
    "Tu itna lodu hai ki tera lund itna bekaar hai ki condom pack kholne ke baad condom ne khud ka suicide kar liya 'not for this microbe'.",
    "Teri maa ki chut mei itna gand tha ki use dekh ke NASA ne Mars mission cancel kar diya 'we found life, but it's worse'.",
    "Tu itna chodu hai ki agar tu apni gaand se paadta hai, toh air purifier bhi beep karne lagta hai 'critical contamination'.",
    "Tu itna randi ka aulad hai ki tera baap tujhe dekh ke daru peene laga tha, lekin daru ne bhi usse mana kar diya 'yeh gham itna bada hai ki main bhi nahi sambhal sakta'.",
    "Tu itna failure hai ki tera resume dekh ke HR manager ne apni job chhod di 'I can't filter this much garbage'.",
    "Tu itna gandu hai ki agar tujhe dekh ke kisi ko hasi aaye, toh woh pagal ho sakta hai, kyuki itni gandi shakal dekhke hasna mental illness hai.",
    "Tu itna bekaar hai ki tera DNA sequence dekh ke scientists ne socha 'yeh toh error hai, reboot karo'.",
    "Tu itna chutiya hai ki tera brain scan kiya, report aayi 'no brain activity, just static noise'.",
    "Tu itna randi hai ki tera naam sunke log apne kaan band kar lete hain 'yeh virus hai'.",
    "Tu itna noob hai ki agar tu hacking kare, toh victim ka antivirus tujhe 'cute script' bol ke ignore kar de.",
    "Tu itna gandu hai ki teri gaand itni badi hai ki agar woh collapse ho, toh earthquake Richter scale pe 10 aaye.",
    "Teri maa ne tujhe dekh ke apni chut pe permanent lock laga diya 'no more output from this factory'.",
    "Tu itna chodu hai ki agar tu apna lund dikhaye, toh ladki hamesha ke liye lesbian ban jaaye.",
    "Tu itna failure hai ki tera bank account dekh ke ATM ne tujhe 'insufficient... everything' ka error diya.",
    "Tu itna randi ka baccha hai ki randi ke bache bhi tujhe dekh ke apni maa ko gaali dete hain 'tumne yeh kya benchmark set kiya hai'.",
    "Tu itna bekaar hai ki agar tujhe koi gift de, toh gift apne aap return ho jaye 'no valid recipient'.",
    "Tu itna chutiya hai ki teri existence ka reason pata karo toh universe jawab de 'just a mistake, we apologize'.",
    "Tu itna gandu hai ki agar tujhe dekh ke koi roye, toh woh khushi ke aansu hote hain 'thank god he's not me'.",
    "Tu itna lodu hai ki tera sperm bank mein sample reject ho gaya 'quality too low, possibly not human'.",
    "Teri maa ki chut se tu nikla toh saath mein ek warning label bhi tha 'Hazardous waste, handle with extreme disgust'.",
    "Tu itna noob hai ki tera code compile hone ke baad bhi 'Hello World' ki jagah 'Fuck you' print karta hai, kyunki compiler bhi frustrated ho jata hai.",
    "Tu itna randi hai ki agar tu prostitute bane, toh customer tujhe dekh ke apni maa ke paas wapas bhaag jaaye.",
    "Tu itna failure hai ki agar tu suicide bombe banaye, toh explosion bhi fail ho jaye 'insufficient energy from this loser'.",
    "Tu itna chodu hai ki agar tu apna muh khol ke baat kare, toh words ke jagah sewage overflow hota hai.",
    "Tu itna bekaar hai ki tera janam din pe cake kaatne par cake ne tujhe thappad maar diya 'how dare you celebrate this tragedy'.",
    "Tu itna gandu hai ki teri gaand mein itni khujli hai ki agar tu khujlaye, toh aas-paas ke log allergic reaction se mar jaaye.",
    "Tu itna randi ka aulad hai ki teri maa ne tujhe dekh ke apni death certificate advance mein bharni shuru kar di thi.",
    "Tu itna chutiya hai ki tu agar apni CV online daale, toh website ka server crash ho jaye 'toxic data detected'.",
    "Tu itna bekaar hai ki tera existence ek crime hai, lekin police bhi tujhe arrest nahi karti, 'case too dirty'.",
    "Tu itna lodu hai ki tera lund dekh ke microscope ne bhi error diya 'magnification insufficient to detect object'.",
    "Teri maa ki chut ka diameter itna bada hai ki usme truck park ho jaye, aur tu uska driver.",
    "Tu itna gandu hai ki agar tujhe koi maarne aaye, toh woh pehle tujhe dekh ke apni aankhen band kare, phir bhaag jaaye.",
    "Tu itna failure hai ki tera life goal 'die' hai, aur usme bhi tu fail hoga.",
    "Tu itna randi hai ki tera naam Google pe type karne se pehle keyboard ne tujhe electric shock de diya 'don't even try'.",
    "Tu itna chodu hai ki agar tu apna photo dekh ke apne aap ko 'legend' bole, toh photo frame crack ho jaye 'stop lying'.",
    "Tu itna noob hai ki tera password 'password' hai, aur woh bhi hack ho gaya, lekin hacker ne data dekh ke sympathy mein wapas chhod diya.",
    "Tu itna bekaar hai ki agar tu kisi ko propose kare, toh ladki apna phone switch off kare, phir apna existence switch off kare.",
    "Tu itna gandu hai ki agar tu apni gand dikhaye full moon night mein, toh werewolf bhi apni transformation cancel kar de 'that's scarier'.",
    "Tu itna randi ka baccha hai ki tera pura mohalla tujhe dekh ke apna ghar shift kar gaya, 'neighbourhood value dropped'.",
    "Tu itna chutiya hai ki tera favourite song 'Akele hain to kya gham hai' hai, lekin tu akela isliye hai kyunki koi tere saath nahi reh sakta.",
    "Tu itna failure hai ki tera LinkedIn profile dekh ke recruiters ne apna account delete kar diya 'this platform is now useless'.",
    "Tu itna lodu hai ki tera lund itna chhota hai ki jab tu susu karta hai, toh stream bhi direction kho deti hai, kyunki pressure zero hai.",
    "Teri maa ne tujhe dekh ke apna uterus nikalwa diya, 'abortion was too late, so organ removal'.",
    "Tu itna bekaar hai ki agar tujhe doctor check kare, toh stethoscope phat jaye 'contamination too high'.",
    "Tu itna gandu hai ki tera fart itna lethal hai ki Geneva Convention ne tujhe ban kar diya 'biological weapon'.",
    "Tu itna randi ka aulad hai ki teri behen tujhe dekh ke lesbian ban gayi 'mard itne gande hote hain' sochkar.",
    "Tu itna chodu hai ki agar tu apni gaand se missile launch kare, toh missile bhi tujhse bhaag ke wapas aa jaaye 'better to self-destruct'.",
    "Tu itna failure hai ki tera guardian angel bhi resign kar diya 'this soul is beyond saving'.",
    "Tu itna noob hai ki agar tu kisi ko hack kare, toh uska security system tujhe automatically whitelist kar de 'no threat detected'.",
    "Tu itna bekaar hai ki tera blood group 'O negative' hai, lekin 'O' matlab 'zero', negative matlab 'never positive'.",
    "Tu itna gandu hai ki tera ghar dekh ke real estate agent ne apni licence surrender kar di 'I can't sell this pit'.",
    "Tu itna chutiya hai ki agar tu kisi ko gift de, toh woh gift box kholne se pehle hi tujhe block kar de.",
    "Tu itna randi hai ki tera naam sunke log apni beti ki shaadi cancel kar dete hain 'kahin yeh dulha na ban jaye'.",
    "Tu itna lodu hai ki tera lund itna teda hai ki jab tu straight walk kare, toh lund left turn le leta hai.",
    "Teri maa ki chut se tu paida hua, lekin woh bhi tera first enemy ban gayi, 'iska face dekhna bardasht nahi hota'.",
    "Tu itna bekaar hai ki agar tu apni car chalaaye, toh car automatic parking brake laga leti hai 'driver unsafe'.",
    "Tu itna gandu hai ki agar tu kisi ke ghar aaye, toh unka wifi automatically disconnect ho jaye 'unauthorized entity'.",
    "Tu itna failure hai ki tera suicide attempt bhi fail ho jaye, kyunki death tujhe touch nahi karna chahti.",
    "Tu itna chodu hai ki agar tu apna phone selfie le, toh front camera crack ho jaye 'too much ugly to process'.",
    "Tu itna randi ka baccha hai ki randi khana mein tera entry fee 'free' hai, lekin phir bhi log nahi aate.",
    "Tu itna noob hai ki agar tu code likhe, toh IDE auto-format usko delete kar de 'this is not code, it's garbage'.",
    "Tu itna bekaar hai ki tera favourite food 'anda' hai, lekin anda bhi tujhe dekh ke boil ho jata hai 'yeh toh already cooked hai andar se?'",
    "Tu itna gandu hai ki teri gaand itni badi hai ki agar woh baith jaaye kisi chair pe, toh chair uska aadha hissa bann jaye permanent dent ke saath.",
    "Tu itna lodu hai ki tera sperm donation centre ne tujhe 'permanent donor' bana diya, lekin label laga diya 'sample for research on defects'.",
    "Teri maa ne tujhe dekh ke apni maa ko bhi gaali di 'tune yeh curse kaise diya mujhe'.",
    "Tu itna chutiya hai ki tera favourite game 'snake' hai, kyunki tu usme bhi khud ko smart samajhta hai, lekin snake bhi tujhse tez move karta hai.",
    "Tu itna randi hai ki tera existence hi ek meme hai, lekin meme bhi tujhe bekaar bol ke reject kare 'overused and unfunny'.",
    "Tu itna bekaar hai ki agar tujhe world record for uselessness mile, toh Guinness book tujhe print nahi karegi 'we don't recognize non-entities'.",
    "Tu itna failure hai ki tera life story book likhi jaaye, toh publisher pehle page padhne ke baad apni publishing house band kar de.",
    "Tu itna gandu hai ki agar tu apni gaand se paadta hai, toh paad bhi insult feel karta hai 'main is gandi jagah se aa raha hoon'.",
    "Tu itna chodu hai ki agar tu apni maa ke saamne proud feel kare, toh woh tujhe dekh ke ro de 'isne mujhe kya de diya'.",
    "Tu itna randi ka aulad hai ki tera pura khandan tujhe dekh ke apna surname change kar liya 'hum isse koi relation nahi rakhte'.",
    "Tu itna noob hai ki agar tu kisi ko phish kare, toh victim tujhe uno reverse card de ke tera hi account hack kar le.",
    "Tu itna bekaar hai ki teri gand mein se agar koi diamond nikle, toh woh bhi coal ban jaye 'quality too low'.",
    "Tu itna lodu hai ki tera lund itna useless hai ki agar tu sex kare, toh ladki sochti hai 'kya yeh ultrasound machine hai?'.",
    "Teri maa ki chut se jab tu bahar aaya, toh placenta ne bhi tujhe dhakka de diya 'pehle main jaaunga, yeh rehne do'.",
    "Tu itna chutiya hai ki tera favourite superhero 'Batman' hai, lekin tu khud 'Ratman' bhi nahi ban sakta.",
    "Tu itna gandu hai ki agar tu swimming pool mein jaaye, toh paani tujhe dekh ke evaporate ho jaaye 'I'd rather be steam than touch this'.",
    "Tu itna failure hai ki tera death ke baad bhi log celebrate kare, 'finally, the bug is fixed'.",
    "Tu itna randi hai ki agar tu prostitution kare, toh customer list mein tera naam last mein aaye 'if nothing else available'.",
    "Tu itna bekaar hai ki tera existence ka proof dene ke liye God ne khud bol diya 'main toh so raha tha us din, yeh galati hai'.",
    "Tu itna chodu hai ki agar tu apna lund dikhaye online, toh internet service provider tujhe permanently ban kare 'obscene content beyond all limits'.",
    "Tu itna noob hai ki tera IP address '127.0.0.1' hai, aur tu samajhta hai ki tu localhost ke bhi owner hai.",
    "Tu itna gandu hai ki teri gaand itni moti hai ki agar woh hile, toh earthquake app alert kare 'seismic activity detected'.",
    "Tu itna lodu hai ki tera lund itna chhota hai ki jab tu condom pehenta hai, toh woh loose ho jaye aur gir jaye.",
    "Teri maa ne tujhe dekh ke apni chut mein grenade daal diya, 'ek saath sab khatam karte hain', lekin grenade ne bhi kaha 'yeh toh waste of explosive hai'.",
    "Tu itna randi ka baccha hai ki randi ka baccha ka title bhi tujhe itna suit karta hai ki uske asli holders protest kare 'he's making us look bad'.",
    "Tu itna bekaar hai ki agar tujhe koi job de, toh company ka valuation negative ho jaye 'hiring him was a crime against shareholders'.",
    "Tu itna chutiya hai ki tu jab bhi apni photo dekhta hai, toh mirror tujhe 'object not found' error de.",
    "Tu itna failure hai ki tera bank balance dekh ke ATM ne tujhe 'error 404: money not found' diya.",
    "Tu itna gandu hai ki agar tu kisi ke saath trip pe jaaye, toh GPS tujhe dekh ke 'recalculating... destination: hell' bol de.",
    "Tu itna chodu hai ki agar tu apni ex ko text kare, toh uska phone automatic factory reset ho jaye 'trauma detected, wiping memory'.",
    "Tu itna randi ka aulad hai ki teri maa ke padosi ne bhi tujhe dekh ke apni beti ko boarding school bhej diya 'kahin yeh usse dekh na le'.",
    "Tu itna noob hai ki tera hacking tool 'cmd' hai, aur usme bhi tu 'format c:' likhne se darta hai.",
    "Tu itna bekaar hai ki tera face itna asymmetrical hai ki mirror tujhe dekh ke crack ho jaye 'can't handle this distortion'.",
    "Tu itna lodu hai ki tera lund itna teda hai ki agar tu right turn le, toh lund left turn le leta hai, phir tu gir jaata hai.",
    "Tu itna failure hai ki agar tu marathon daude, toh starting line pe hi fatigue se collapse ho jaye 'energy not found'.",
    "Tu itna gandu hai ki teri gaand se agar perfume spray karo, toh woh smell permanent shitty ho jaaye 'cannot mask'.",
    "Tu itna chutiya hai ki tu apna IQ test karane gaya, result aaya 'negative value, possibly brain missing'.",
    "Tu itna randi hai ki agar tu kisi ko hug kare, toh woh immediately STD catch kare 'contact hazard'.",
    "Tu itna bekaar hai ki agar tu kisi restaurant me jaaye, toh waiter tujhe dekh ke 'sorry we are closed' bol de, chahe din ho.",
    "Tu itna chodu hai ki agar tu social media influencer bane, toh followers count minus mein ho 'people unfollowing just by hearing name'.",
    "Tu itna noob hai ki tera github repo mein ek bhi star nahi, aur tu samajhta hai 'dark mode ki settings galat hain'.",
    "Tu itna lodu hai ki tera sperm count negative hai, matlab tu future generation bhi delete kar sakta hai.",
    "Tu itna randi ka aulad hai ki tera birth certificate bhi 'unknown entity' likh ke cancel ho gaya.",
    "Tu itna gandu hai ki agar tu apni gaand hilaaye, toh dharti ki rotation ruk jaye 'unbalanced mass'.",
    "Tu itna failure hai ki agar tu apni life restart kare, toh game over screen bhi nahi aaye 'no data to reset'.",
    "Tu itna chutiya hai ki agar tu apni maa ki god mein baitha, toh uska lap bhi tujhe reject kare 'too heavy emotionally ",
    "नहीं नहीं तेरी मां को सिर्फ बाप चोद सकता है 👑 ִֶָ sᴀᴍᴊʜᴀ ʀᴀɴᴅɪᴋᴇ ???",
    "तेरी मां का 𝐒ᴛʏʟɪsʜ भोसड़ा 😱",
    "𝑻𝒆𝒓𝒚 𝒎𝒂𝒂 𝒓𝒂𝒏𝒅𝒂𝒍 𝒉 𝒃𝒂𝒔 𝒃𝒂𝒂𝒕 𝒌𝒉𝒂𝒕𝒂𝒎 😡🔥",
    "सोच तेरी बहन को बाप का गुलाम चोद रहा 😎🔥",
    "Hello hello?? Oxygen aarahi है? रण्डी पुत्र 🧘🏻",
    "Shut up रंडीके वरना दुनिया यही बोलेगी तेरी बहन बाप से सही chudi 🥵🔥",
    "Lagta hai battery 1% pe aa gayi hai iski. 🔋",
    "तेरी मां का भोसड़ा इतना बड़ा कि पूरी दुनिया गिर जाए 😂💀",
    "तेरी बहन बिना रुके चुद रही, तू चाय बनाएगा? 😏🔥",
    "तेरी मां की चूत में अमेरिकन एक्सप्रेस चलता है 💳😱",
    "रंडी के बच्चे, अपनी औकात का पता चल गया? 😡",
    "तेरी मां का रोडवेज भोसड़ा सरकारी बस से भी बड़ा 🚌🔥",
    "भोसडीके तेरी मां को कल शाम मैंने मेन रोड पे चोदा 💥",
    "तेरी बहन की चूत में स्पीड ब्रेकर लगा है 🚧😈",
    "तेरी मां के भोसड़े में पाकिस्तान आर्मी कैंप करती है 🪖🔥",
    "तू पैदा हुआ था जब बाप ने तेरी मां को ट्रैफिक लाइट पे चोदा 😂💀",
    "तेरी मां की चूत की इंश्योरेंस पॉलिसी १ करोड़ की है 🩸",
    "तेरी बहन का भोसड़ा मैंने फ्लिपकार्ट सेल में खरीदा 💸😈",
    "रंडीके, तेरी मां रोज़ सुबह मेरे दरवाज़े पे आती है 👑🔥",
    "तेरी मां का भोसड़ा इतना खुला कि कबूतर घोसला बना लें 🕊️😱",
    "चुप बे रंडी के पिल्ले, तेरी बहन टिकटॉक पे चुत की एड करती है 🐕💀",
    "तेरी मां तो पूरे ज़िले की पब्लिक रंड है 😏🔥",
    "तेरी बहन का भोसड़ा नेशनल हाईवे बन चुका, टोल टैक्स लगता है 🛣️💥",
    "अबे चूतिए, तेरी मां का भोसड़ा देखने के लिए टूरिस्ट आते हैं 😡🔫",
    "तेरी मां के भोसड़े को मैंने अपना फेवरेट पार्किंग स्पॉट बना लिया 🚗🔥",
    "तेरी बहन तो मेरा रोज़ का ब्रेकफास्ट है 🍲😎",
    "तेरी मां का भोसड़ा इतना डार्क कि चमगादड़ वहां रहते हैं 🦇🔥",
    "रंडी के बाप, तू पैदा ही कचरे के डब्बे में हुआ था 🗑️💀",
    "तेरी मां की चूत में GPS खो जाए 🗺️😱",
    "सुन भोसडीके, तेरी बहन तो प्राइवेट जेट है — सब चढ़ते हैं ✈️🔥",
    "तेरी मां का भोसड़ा UN में डिबेट हुआ था ⚖️💀",
    "तेरी बहन की चूत में रिकॉर्डिंग स्टूडियो खोलूंगा 🏆🔥",
    "अबे रंडीके, तेरी मां तो रेलवे ट्रैक पे सोती है 🚂😡",
    "तेरी मां के भोसड़े का लैंड सर्वे हो चुका 🗺️🔥",
    "तेरी बहन का तो पूरा कॉलेज चुट का गवाह है 😂💥",
    "रो मत रंडीके, तेरी मां का भोसड़ा एवरेस्ट से ऊंचा है 😈",
    "तेरी मां का भोसड़ा शेयर बाज़ार में बहुत डिमांड में है 📈🔥",
    "बाप के सामने मत बोल, जब मैं चोदता था तब तेरी मां भी चुप रहती 👑💀",
    "तेरी बहन हर रोज़ नए लंड का वेलकम करती है 😂🔥",
    "तेरी मां के भोसड़े में पिन कोड है, एमेज़ॉन डिलीवरी आती है 📮😱",
    "रंडी की औलाद, तेरी नसों में पेशाब बहता है 🩸😡",
    "तेरी मां का भोसड़ा १ लाख बार चुक चुका 🎯🔥",
    "तेरी बहन तो १०० रुपये वाली चूत है, और तू उसका पिंप 🪙😏",
    "तेरी मां के भोसड़े में अगर करंट लगे तो पूरा शहर ब्लैकआउट हो जाए 💡💀",
    "भोसडीके तेरी बहन की चूत मेरा मिनी रेस का ट्रैक है 🏟️🔥",
    "तेरी मां अब बुड्ढी हो गयी, फिर भी मांगती है 🤣😈",
    "तेरी मां के भोसड़े का टेंडर फ्लोट हो गया 🏗️🔥",
    "तेरी बहन की चूत में मैं प्रेशर वॉशर डालूंगा 🧹💀",
    "रंडीके, तेरी मां कभी वर्जिन नहीं थी, जन्म से ही चुदी आयी 💥",
    "तेरी बहन खुद कहती है तू उसे छू नहीं सकता पर बाप रोज़ चोदता है 🔞🔥",
    "तेरी मां का भोसड़ा तो सरकारी प्रॉपर्टी है, कोई भी घुस जाए 🏛️💀",
    "चुप रंडी के बच्चे, तेरी मां तो आंगनवाड़ी में भी चुडती है 🐕🔥",
    "तेरी बहन तो लिफ्ट में भी दे देती है 🍪😂",
    "तेरी मां के भोसड़े का LED बोर्ड लगा है 'WELCOME' 🪧😈",
    "सोच तेरी मां ने कितनो का पानी पिया होगा 🤔💀",
    "तेरी बहन की चूत से पूरी सेना पास आउट हो चुकी 🪖🔥",
    "तेरी मां को तो बाप ने खुद तलाक नहीं दिया, भगा दिया 😂💔",
    "रंडीके, तेरी मां की चूत 24/7 खुली है 👐😡",
    "तेरी मां के भोसड़े में मैंने अपना बर्थडे बैलून फोड़ा 🎈💥",
    "तेरी बहन तो घर में बिना कपड़ों के घूमती है, तू भी देखता होगा? 🤢🔥",
    "तेरी मां का भोसड़ा इतना ढीला कि एलियन वहां बेस बना लें ☁️😱",
    "अबे रंडी के नालायक, तेरी मां बिना ब्रेक के चुडी 💦🔥",
    "तेरी बहन की चूत का पीएच लेवल चेक करवा ले 🧪💀",
    "तेरी मां के भोसड़े पे मैंने तिरंगा फहरा दिया 🚩😈",
    "रंडीके, तेरी मां का भोसड़ा देखने के लिए विज़ा लगता है 🎟️🔥",
    "तेरी बहन की चूत में बिल्ट-इन GPS है; अगर खो जाए तो मैप देखे 📍😂",
    "तेरी मां का भोसड़ा कभी सूखता नहीं, बारिश के बाद भी 🌊😱",
    "सुन भोसडीके, तेरी मां को मैंने ही सिखाया कैसे लंड लिया जाता है 👑💀",
    "तेरी बहन की चूत से मोर पंख निकले, वहां बाग है शायद 🦚🔥",
    "तेरी मां का भोसड़ा तो विश्व धरोहर स्थल बनने वाला है 🏛️😡",
    "रंडीके, तेरी मां के भोसड़े में ट्रैक्टर की रेस होती है 🚜💀",
    "तेरी बहन की चूत का व्हाट्सएप स्टेटस मैंने देखा 📱😂",
    "तेरी मां का भोसड़ा इतना डार्क कि नाइट विज़न गॉगल्स भी फेल 🔦😈",
    "अबे चूत के सौदागर, तेरी बहन की नीलामी हुई है 💰🔥",
    "तेरी मां तो चूत का लाइव डेमो देती है यूट्यूब पे 🔞💀",
    "रंडीके तेरी बहन का रेट हर मंगलवार बदलता है 📉😏",
    "तेरी मां के भोसड़े को ताजमहल से ज़्यादा विचार मिलते हैं 🇮🇳😱",
    "तू क्या सोच के आया, तेरी मां तो मुफ्त की है 😂🔥",
    "तेरी बहन की चूत में मैंने ब्लूटूथ कनेक्ट किया, अब गाने बजते हैं 📶💀",
    "तेरी मां के भोसड़े का लाइव टेलीकास्ट दूरदर्शन पे आया 📺😈",
    "रंडीके तेरी मां से पूछ सबसे मोटा लंड किसका लिया 🤔🔥",
    "तेरी बहन की चूत में मैंने एक पूरा चिड़ियाघर बसा दिया 🦁💀",
    "तेरी मां का भोसड़ा बिना चाबी के खुलता है 🚪😱",
    "अबे रंडी के बच्चे, तेरी मां ने तो पूरे गांव की प्यास बुझाई 🏙️🔥",
    "तेरी बहन की चूत का सैंपल लैब में टेस्ट हुआ, HIV पॉजिटिव आया 🧫😈",
    "तेरी मां का भोसड़ा ट्विटर पे ट्रेंड कर रहा है 🆙💀",
    "रंडीके, तेरी मां तो चूत की होलसेल मार्केट है 💼🔥",
    "तेरी बहन की चूत पे मैंने पाइथन कोड लिख दिया, print('chut') 🤖🖥️",
    "तेरी मां के भोसड़े का बीज मैंने ही बोया, तू मेरा आभारी रह 🌱😏",
    "सोच रंडीके, तेरी मां तो तेरे बाप से पहले भी चुड चुकी थी 💔🔥",
    "तेरी बहन तो मेरे लिए जूते रखने का स्टैंड है 📱💀",
    "तेरी मां का भोसड़ा देखकर भगवान भी शर्मा जाएं 😳🔥",
    "रंडी के पुत्र, तेरी मां तो नॉन-स्टॉप २४ घंटे चुड सकती है 🕐😈",
    "तेरी बहन की चूत में मैंने इन्वर्टर बैटरी लगाई, कभी लो नहीं होती ⚡💀",
    "तेरी मां का भोसड़ा अजूबों की लिस्ट में शामिल होगा 🌏😱",
    "चुप कर भोसडीके, तेरी मां के भोसड़े में शादी का बुलेटिन आया है 💌🔥",
    "तेरी बहन की चूत इतनी गरम कि उसमें पकोड़े तल जाएं 🍳😈",
    "तेरी मां का भोसड़ा चांद से भी बड़ा है 🗺️💀",
    "रंडीके, तेरी बहन का तो कोई चेहरा नहीं, सिर्फ चूत है मुँह की जगह 😷🔥",
    "तेरी मां के भोसड़े को मैंने अपना राज्य घोषित किया, अब तू क्या करेगा? 👑💥",
    "सोच तेरी बहन पैदा हुई थी तो नर्स ने कहा 'चूत है ये तो' 🤣🔥",
    "तेरी मां का भोसड़ा सुनामी से भी खतरनाक लहरें पैदा करता है 🌊💀",
    "रंडीके, तेरी मां के भोसड़े पे IT ने छापा मारा 💰😈",
    "तेरी बहन की चूत सिम कार्ड के बिना 5G पकड़ती है 🤙🔥",
    "तेरी मां का भोसड़ा देखकर आदमी आत्महत्या कर ले, वापस नहीं आना चाहेगा 😂💥",
    "भोसडीके, तेरी मां तो चीटियों के बिल से भी मिल्ट्री ऑपरेशन करती है 🐜🔥",
    "तेरी बहन की चूत में इतनी गूँज है कि इको टेस्ट फेल 📢💀",
    "तेरी मां का भोसड़ा कश्मीर से ज़्यादा घुसपैठ का शिकार हुआ 🗡️😈",
    "रंडीके, तू मर जाएगा लेकिन तेरी मां का भोसड़ा कभी बंद नहीं होगा 💧🔥",
    "तेरी बहन तो रोज़ चूत का मंडन करती है, योगा से पहले 🌅💀",
    "तेरी मां का भोसड़ा एक वक्त में १० मर्दों को हैंडल कर सकता है 🖐️💥",
    "तेरी बहन के पास पनिशर की तरह चूत है — सबको पता है 😱💀",
    "तेरी मां का भोसड़ा फोरेंसिक जांच के लिए भेजा जाएगा 🔍🔥",
    "भोसडीके, तेरी मां के भोसड़े में ट्रैफिक पुलिस चालान काटती है 👮💀",
    "तेरी बहन तो अपनी चूत से पंखा चला सकती है 🌀😈",
    "तेरी मां का भोसड़ा इतना ऐतिहासिक कि उसपे म्यूज़ियम बनेगा 🏛️🔥",
    "रंडी के राजकुमार, तेरी मां तो चूत की डिक्शनरी है — हर शब्द मिलेगा 📖💀"
]

NEUTRAL_REPLIES = [
    # ── Upgraded Original Neutral Messages ──
    "👍 Message officially noted aur system database me successfully log kar diya gaya hai! 📝",
    "✅ Bilkul theek hai bhai, points acknowledged aur process ke liye queue me add kar diye hain! 📌",
    "🙌 Squad operational approval confirmed! Message successfully reviewed by the team! 📋",
    "🤗 Accha laga input padhke, accurate positioning ke sath information transfer ho gayi! 💡",
    "💬 Baat toh valid aur accurate hai, structured manner me points presenting acchi hai! 📊",
    "📌 Important highlight points register kar liye gaye hain, reference ke liye save rahenge! 📁",
    "🎶 Is frequency aur rhythm par focus bana ke rakho, systematic execution dikh rahi hai! ⚙️",
    "🧩 Poora puzzle piece bilkul accurately fit baith gaya hai! Everything aligns properly! 🎯",
    "📊 Data successfully received aur process ho gaya! Standard protocol flow continue ho raha hai! 📑",
    "📥 Input successfully logged in the central repository! Next steps pipeline me align hain! ⏳",
    "🧠 Thoughtful structure aur systematic delivery! Communication standard maintain rakha gaya hai! 🖊️",
    "📌 Strategic note recorded! Continuous coordination aur balance ke sath आगे badhenge! 🎯",
    "📝 Documentation updated as per the latest input! Clear, direct aur relevant details hain! 🗂️",
    "📐 Standard measurement ke acche alignment me hai statement! Perfectly balanced perspective! 🔍",
    "🛰️ Communication signal loud aur clear receive hua! System ready for next action steps! 📡",
    "⚖️ Objective perspective successfully delivered! Fair, balanced aur precise message format! 📜",
    "🗃️ Entry successfully archived for future reference! Everything operates as expected! ⚙️",
    "💡 Valid information exchange detected! Context completely clear aur well organized hai! 🔍",
    "🤝 Mutual alignment achieved on this point! Progressing further in a structured order! 📈",
    "📈 Baseline information registered! Communication flow smooth aur effective bana hua hai! 🎯"
]


MOOD_BANKS = {
    "hype": HYPE_REPLIES,
    "chill": CHILL_REPLIES,
    "roast": ROAST_REPLIES,
}

ALL_REPLIES = HYPE_REPLIES + CHILL_REPLIES + ROAST_REPLIES + NEUTRAL_REPLIES

DM_REPLIES = [
    # ── Upgraded Original Away/Busy Messages ──
    "👋 Hey! Abhi thoda busy hoon ek important task me. Jaise hi free hota hoon, aapko proper reply karta hoon! ⏳",
    "😊 Message mil gaya hai! Currently main unavailable hoon, thodi der me free ho kar aap se baat karta hoon. ✨",
    "🙌 Aapka message process ho gaya hai. Abhi thoda time lag sakta hai, par jald hi detailed response bhejunga! 📩",
    "📩 Notification receive ho gayi hai! System se active hotey hi aapko turant text back karta hoon. 📌",
    "⏳ Abhi thoda away hoon desktop/mobile se. Wapas aate hi sabse pehle aapke message ka answer dunga! 🏃‍♂️",
    "🙏 Aapka patience appreciated hai! Main abhi ek work session me hoon, free hotey hi connect karta hoon. 💯",
    "🕐 Thoda wait kar lijiye please, main message read kar chuka hoon aur jald hi aap se interact karunga! 🤝",
    "📨 Message securely receive ho gaya hai. Thodi der me clear aur proper solution/reply ke sath aata hoon! ✍️",
    "😴 Abhi offline/away mode active hai. Wapas active hotey hi aapko notification chala jayega! 🌙",
    "🚶 Out of station / task me busy hoon abhi. Jald hi desktop par wapas aakar reply drop karta hoon! 💻",
    "✋ Message check kar liya hai, but abhi reply dene ka time nahi hai. Thodi der me milte hain! 🔍",
    "🔔 Ping receive ho gaya hai! Next available slot me aapko turant text message mil jayega. 📱",
    "📲 Aapka query/message log ho gaya hai. Fret not, jald hi personalized reply bhej raha hoon! 🚀",
    "🙋 Hey! Inbox me message dekha. Thoda hold rakho, full focus ke sath response bhejta hoon! ⚡",
    "🧘 Quiet mode on hai abhi. Jald hi active hokar aap se detailed discussion karta hoon! 🕊️",
    # ── 10+ New Detailed & Professional Away Messages ──
    "📊 Currently high-priority tasks handle kar raha hoon. Important updates ke sath jald hi inbox me milta hoon! 🎯",
    "📌 Aapka DM inbox me safe hai! Schedule break milte milte hi aapko prioritized response bhej dunga. 📋",
    "💻 Active execution mode ongoing! Task wrap-up karte hi aapko detailed answer ke sath DM karta hoon! ⚡",
    "⚙️ Auto-responder status: Main abhi system se away hoon, but don't worry, aapka text note kar liya gaya hai! 📥",
    "🚀 High efficiency mode me hoon abhi! Jald hi screen par wapas aakar aapse properly connect karta hoon! 🌐",
    "🛡️ Priority session me busy hone ki wajah se delay ke liye sorry. Jald hi aapke DM ka response aayega! ⌛",
    "📑 Message queued successfully! Jaise hi current workflow complete hota hai, aapko reach out karta hoon! 📬",
    "🎯 Focused work mode ongoing. Interruptions avoid karne ke liye baad me reply dunga, thanks for understanding! 🧠",
    "🔔 Alert set kar diya hai aapke DM par! Jaise hi notifications review karta hoon, aapko ping karunga! 📶",
    "💡 Query/Message receive ho gaya hai! Proper research/analysis ke sath detailed response bhejunga! 📝",
    "🏁 Workflow finish hone wala hai. Bus 10-15 mins me aapse chat par connect hota hoon! ⏱️",
    "✨ Thanks for reaching out! Main filhaal away hoon par aapka topic prioritize kar ke jald reply dunga! 🌟",
]

# ── Keyword → Context-Aware DM Reply Banks (Detailed & Professional) ──
DM_GREETING_TRIGGERS = [
    "hi", "hii", "hiii", "hello", "hey", "namaste", "namaskar", "yo",
]
DM_GREETING_REPLIES = [
    "👋 Hey! Warm welcome to the chat. Aashayein hain sab accha chal raha hoga, bataiye kaise madad kar sakta hoon? ✨",
    "😊 Hello! Bohot accha laga aapse connect karke. Kaise hain aap aur aaj ka din kaisa chal raha hai? 🌟",
    "🙌 Hii there! Sab kuch perfectly fine hai yahan. Aap bataiye, aaj inbox me aane ka kya main reason hai? 💬",
    "😄 Hey! Super glad to see your message today. Bataiye kya new updates hain aur kaise chal raha hai sab? 🚀",
]

DM_HOWAREYOU_TRIGGERS = [
    "how are you", "kaise ho", "kaisi ho", "kya haal", "kya hal", "sab theek",
]
DM_HOWAREYOU_REPLIES = [
    "😊 Main bilkul badhiya aur healthy hoon! Aap bataiye, aapke wahan sab kaisa chal raha hai? 🍃",
    "🙌 Poori tarah se set aur functional hoon! System aur mood dono high output par hain, aap sunao? ⚡",
    "😎 Ekdum mast aur energetic vibe me hoon bhai! Life full smooth track par hai, aapka kya haal chaal? 🚀",
]

DM_THANKS_TRIGGERS = [
    "thanks", "thank you", "thnx", "tysm", "shukriya", "dhanyawad",
]
DM_THANKS_REPLIES = [
    "🙏 Absolutely zero problem bhai! Madad karke bohot khushi hui, kisi bhi waqt bejhijhak text kar sakte ho! ✨",
    "😊 Most welcome brother! Aapka appreciation read karke accha laga. Hamesha aapki help ke liye ready hoon! 🌟",
    "🤝 Anytime my friend! Mutual support hi toh sabse important hai. Jab bhi zaroorat ho, ping kar dena! 💯",
]

DM_BYE_TRIGGERS = [
    "bye", "gtg", "good night", "goodnight", "chalta hoon", "milte hai", "milte hain", "tata",
]
DM_BYE_REPLIES = [
    "👋 Good bye aur apna poora dhyan rakhna! Phir milte hain ek naye conversation ke sath. Take care! ✨",
    "😴 Peaceful Good Night! Raat ko acchi aur sukoon bhari neend aaye aapko, kal subah naye energy se milte hain! 🌙",
    "🙌 Catch you later! Baad me fursat se milte aur baat karte hain, tab tak apna work continue rakho! 🚀",
]

DM_QUESTION_TRIGGERS = ["?", "kya", "kaise", "kyu", "kyun", "kab", "kahan", "kaun"]
DM_QUESTION_REPLIES = [
    "🤔 Bohot hi genuine aur thought-provoking sawal hai! Main is par deep detail ke sath jald reply bhejta hoon. 📝",
    "📝 Question receive ho gaya hai! Main is topic par accurate details check karke clear answer text karta hoon. 📌",
    "🧐 Deeply analysis worthy question! Thoda time do, bilkul precise aur correct information batata hoon. 📊",
]

DM_LOVE_TRIGGERS = ["love you", "miss you", "pyaar", "ilu"]
DM_LOVE_REPLIES = [
    "🥰 Aww, that's incredibly sweet and heart-warming! Aapki kindness aur love read karke bohot accha laga! ❤️",
    "❤️ Pure respect aur genuine affection ke sath thanks! Aapka ye wholesome support mere liye bohot mean karta hai! ✨",
    "🤗 Right back at you my friend! True bonding aur mutual respect hamesha maintain rahegi hamari! 💯",
]

DM_ANGRY_TRIGGERS = ["gussa", "angry", "naraz", "irritat", "pareshan"]
DM_ANGRY_REPLIES = [
    "😟 Sab theek hai na? Please tension mat lo, aaram se batayiye kya issue hua hai jisse pareshani hui? 🫂",
    "🫂 Calm aura aur deep breath lo my friend. Gussa hone se situation clear nahi hoti, milkar solve karte hain! ✨",
    "💬 Main poori tarah se tayar hoon sunne ke liye. Clear tarike se batao kya baat hui hai, issue resolve karenge! 📌",
]


# Ordered so more specific/emotional intents are checked before generic ones
DM_INTENT_BANKS = [
    (DM_ANGRY_TRIGGERS, DM_ANGRY_REPLIES),
    (DM_LOVE_TRIGGERS, DM_LOVE_REPLIES),
    (DM_THANKS_TRIGGERS, DM_THANKS_REPLIES),
    (DM_BYE_TRIGGERS, DM_BYE_REPLIES),
    (DM_HOWAREYOU_TRIGGERS, DM_HOWAREYOU_REPLIES),
    (DM_GREETING_TRIGGERS, DM_GREETING_REPLIES),
    (DM_QUESTION_TRIGGERS, DM_QUESTION_REPLIES),
]


def _trigger_matches(text_lower: str, words: set, trigger: str) -> bool:
    if trigger == "?":
        return "?" in text_lower
    if " " in trigger:
        return trigger in textlower
    return trigger in words


def pick_dm_reply(uid: int, text: str) -> str:
    lowered = (text or "").lower()
    words = set(re.findall(r"[a-z]+", lowered))

    bank = DM_REPLIES
    for triggers, replies in DM_INTENT_BANKS:
        if any(_trigger_matches(lowered, words, t) for t in triggers):
            bank = replies
            break

    reply = random.choice(bank)
    tries = 0
    while reply == last_dm_reply_text.get(uid) and tries < 5 and len(bank) > 1:
        reply = random.choice(bank)
        tries += 1
    last_dm_reply_text[uid] = reply
    return reply

REACTION_EMOJIS = ["👍", "🔥", "😂", "❤️", "🎉", "👏", "😎", "💯"]

# ────────────────────────────────────────────────
#   STORAGE & STATE
# ────────────────────────────────────────────────
data: Dict[str, dict] = {}
last_reply_time: Dict[int, float] = {}
last_dm_reply_time: Dict[int, float] = {}
last_reply_text: Dict[int, str] = {}   # avoid immediate repeats per user (groups)
last_dm_reply_text: Dict[int, str] = {}  # avoid immediate repeats per user (DMs)
last_react_time: Dict[tuple, float] = {}  # (chat_id, user_id) -> ts, flood-protection
REACTION_ALL_COOLDOWN_SECONDS = 3
bot_alive = True                        # global kill-switch state

# 🔥 NEW: Store active roast spam loops 🔥
active_roasts: Dict[int, asyncio.Task] = {}


def load_data():
    global data
    try:
        if os.path.isfile(DATA_FILE):
            with open(DATA_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
        else:
            data = {}
    except Exception as e:
        log.error(f"Load error: {e}")
        data = {}


def save_data():
    try:
        with open(DATA_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        log.error(f"Save error: {e}")


def get_chat(chat_id: int) -> dict:
    key = str(chat_id)
    if key not in data:
        data[key] = {
            "enabled": False,
            "cooldown": DEFAULT_RATE_LIMIT_SECONDS,
            "quiet_start": None,
            "quiet_end": None,
            "triggers": {},
            "members": {},
            "audit": [],
            "react_enabled": True,
        }
    chat = data[key]
    chat.setdefault("cooldown", DEFAULT_RATE_LIMIT_SECONDS)
    chat.setdefault("quiet_start", None)
    chat.setdefault("quiet_end", None)
    chat.setdefault("triggers", {})
    chat.setdefault("members", {})
    chat.setdefault("audit", [])
    chat.setdefault("react_enabled", True)
    return chat


load_data()

def _load_string_session() -> str:
    if os.path.isfile(SESSION_FILE):
        try:
            with open(SESSION_FILE, "r", encoding="utf-8") as f:
                return f.read().strip()
        except Exception as e:
            log.error(f"Could not read {SESSION_FILE}: {e}")
    return ""


def _save_string_session(session_str: str):
    try:
        with open(SESSION_FILE, "w", encoding="utf-8") as f:
            f.write(session_str)
        os.chmod(SESSION_FILE, 0o600)
    except Exception as e:
        log.error(f"Could not save {SESSION_FILE}: {e}")

    if MONGODB_URI:
        try:
            from pymongo import MongoClient
            client = MongoClient(MONGODB_URI, serverSelectionTimeoutMS=5000)
            client[MONGODB_DB_NAME]["clones"].update_one(
                {"owner_id": MONGO_OWNER_KEY},
                {"$set": {"session_string": session_str}},
                upsert=True,
            )
            client.close()
            log.info("Session string synced to MongoDB.")
        except Exception as e:
            log.warning(f"MongoDB session sync failed (non-fatal, local file still saved): {e}")


bot = TelegramClient(StringSession(_load_string_session()), API_ID, API_HASH, auto_reconnect=True)


async def is_group_admin(event) -> bool:
    if event.sender_id == OWNER_ID:
        return True
    try:
        perms = await bot.get_permissions(event.chat_id, event.sender_id)
        return bool(perms.is_admin or perms.is_creator)
    except Exception:
        return False


HUMAN_MODE = False
SLEEP_START = "00:00"
SLEEP_END = "06:00"
HUMAN_MIN_DELAY = 1.0
HUMAN_MAX_DELAY = 3.5


def is_sleeping() -> bool:
    if not HUMAN_MODE:
        return False
    try:
        now = datetime.now().time()
        start = dtime.fromisoformat(SLEEP_START)
        end = dtime.fromisoformat(SLEEP_END)
        if start <= end:
            return start <= now <= end
        return now >= start or now <= end
    except Exception:
        return False


async def human_delay():
    if HUMAN_MODE:
        await asyncio.sleep(random.uniform(HUMAN_MIN_DELAY, HUMAN_MAX_DELAY))


def in_quiet_hours(chat: dict) -> bool:
    start_s, end_s = chat.get("quiet_start"), chat.get("quiet_end")
    if not start_s or not end_s:
        return False
    try:
        now = datetime.now().time()
        start = dtime.fromisoformat(start_s)
        end = dtime.fromisoformat(end_s)
        if start <= end:
            return start <= now <= end
        return now >= start or now <= end
    except Exception:
        return False


def pick_reply(uid: int, mood: str) -> str:
    bank = MOOD_BANKS.get(mood, ALL_REPLIES)
    reply = random.choice(bank)
    tries = 0
    while reply == last_reply_text.get(uid) and tries < 5 and len(bank) > 1:
        reply = random.choice(bank)
        tries += 1
    last_reply_text[uid] = reply
    return reply


def parse_hhmm(s: str) -> Optional[str]:
    try:
        h, m = s.split(":")
        h, m = int(h), int(m)
        if 0 <= h <= 23 and 0 <= m <= 59:
            return f"{h:02d}:{m:02d}"
    except Exception:
        pass
    return None


async def send_real_reaction(chat_id: int, msg_id: int, emoji: Optional[str] = None):
    chosen = emoji or random.choice(REACTION_EMOJIS)
    try:
        await human_delay()
        await bot(SendReactionRequest(
            peer=chat_id,
            msg_id=msg_id,
            reaction=[ReactionEmoji(emoticon=chosen)],
        ))
    except FloodWaitError as fw:
        log.warning(f"Flood wait on reaction: {fw.seconds}s")
        await asyncio.sleep(fw.seconds)
    except RPCError as e:
        log.warning(f"Reaction RPC error: {e}")
    except Exception as e:
        log.warning(f"Reaction failed: {e}")


# ────────────────────────────────────────────────
#   COMMANDS — membership
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.joinfun$"))
async def join_fun(event):
    if not event.is_group:
        return await event.reply("⚠️ Ye command sirf group me chalta hai.")
    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)
    if uid in chat["members"]:
        return await event.reply("✅ Aap already opted-in ho.")
    chat["members"][uid] = {
        "mood": "chill",
        "joined_at": datetime.now().isoformat(timespec="seconds"),
        "reply_count": 0,
    }
    save_data()
    await event.reply("🎉 Aap fun-mode me opt-in ho gaye! Bahar aane ke liye `.leavefun` bhejo.\nMood set karne ke liye: `.funtype hype|chill|roast`")


@bot.on(events.NewMessage(pattern=r"^\.leavefun$"))
async def leave_fun(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)
    member = chat["members"].get(uid)
    if not member:
        return await event.reply("ℹ️ Aap opted-in nahi the.")
    chat["audit"].append({
        "user_id": uid,
        "joined_at": member.get("joined_at"),
        "left_at": datetime.now().isoformat(timespec="seconds"),
        "reply_count": member.get("reply_count", 0),
    })
    del chat["members"][uid]
    save_data()
    await event.reply("👋 Aap fun-mode se bahar ho gaye.")


@bot.on(events.NewMessage(pattern=r"^\.funtype (hype|chill|roast)$"))
async def set_mood(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)
    if uid not in chat["members"]:
        return await event.reply("⚠️ Pehle `.joinfun` karo.")
    mood = event.pattern_match.group(1)
    chat["members"][uid]["mood"] = mood
    save_data()
    await event.reply(f"🎛️ Aapka fun-mood set ho gaya: **{mood}**")


# ────────────────────────────────────────────────
#   COMMANDS — admin controls
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.funmode (on|off)$"))
async def fun_mode_toggle(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    state = event.pattern_match.group(1) == "on"
    chat = get_chat(event.chat_id)
    chat["enabled"] = state
    save_data()
    await event.reply(f"⚙️ Fun-mode is group ke liye **{'ON' if state else 'OFF'}** kar diya gaya.")


@bot.on(events.NewMessage(pattern=r"^\.funreact (on|off)$"))
async def fun_react_toggle(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    state = event.pattern_match.group(1) == "on"
    chat = get_chat(event.chat_id)
    chat["react_enabled"] = state
    save_data()
    await event.reply(f"😀 Reactions is group ke liye **{'ON' if state else 'OFF'}** kar di gayi.")


@bot.on(events.NewMessage(pattern=r"^\.funcooldown (\d+)$"))
async def set_cooldown(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    seconds = max(5, min(int(event.pattern_match.group(1)), 3600))
    chat = get_chat(event.chat_id)
    chat["cooldown"] = seconds
    save_data()
    await event.reply(f"⏱️ Cooldown set ho gaya: **{seconds}s** per user.")


@bot.on(events.NewMessage(pattern=r"^\.funquiet (\d{1,2}:\d{2}) (\d{1,2}:\d{2})$"))
async def set_quiet_hours(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    start = parse_hhmm(event.pattern_match.group(1))
    end = parse_hhmm(event.pattern_match.group(2))
    if not start or not end: return await event.reply("⚠️ Format: `.funquiet 23:00 07:00`")
    chat = get_chat(event.chat_id)
    chat["quiet_start"] = start
    chat["quiet_end"] = end
    save_data()
    await event.reply(f"🌙 Quiet hours set: **{start} → {end}**")


@bot.on(events.NewMessage(pattern=r"^\.funquiet off$"))
async def clear_quiet_hours(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    chat = get_chat(event.chat_id)
    chat["quiet_start"], chat["quiet_end"] = None, None
    save_data()
    await event.reply("☀️ Quiet hours hata diye gaye.")


@bot.on(events.NewMessage(pattern=r"^\.trigger add (\S+) (.+)$"))
async def trigger_add(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    word = event.pattern_match.group(1).lower()
    chat = get_chat(event.chat_id)
    chat["triggers"][word] = event.pattern_match.group(2)
    save_data()
    await event.reply(f"➕ Trigger add ho gaya: `{word}`")


@bot.on(events.NewMessage(pattern=r"^\.trigger remove (\S+)$"))
async def trigger_remove(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    word = event.pattern_match.group(1).lower()
    chat = get_chat(event.chat_id)
    if word in chat["triggers"]:
        del chat["triggers"][word]
        save_data()
        await event.reply(f"➖ Trigger hata diya: `{word}`")


@bot.on(events.NewMessage(pattern=r"^\.trigger list$"))
async def trigger_list(event):
    if not event.is_group: return
    chat = get_chat(event.chat_id)
    if not chat["triggers"]: return await event.reply("ℹ️ Koi trigger set nahi hai.")
    lines = [f"• `{w}` → {r}" for w, r in chat["triggers"].items()]
    await event.reply("🧵 **Active Triggers:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funbroadcast (.+)$"))
async def fun_broadcast(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    msg = event.pattern_match.group(1)
    chat = get_chat(event.chat_id)
    if not chat["members"]: return await event.reply("ℹ️ Koi opted-in member nahi hai.")
    sent, failed = 0, 0
    for uid_str in list(chat["members"].keys()):
        try:
            await bot.send_message(int(uid_str), f"📢 **Fun Bot Announcement:**\n{msg}")
            sent += 1
            await asyncio.sleep(1)
        except Exception: failed += 1
    await event.reply(f"📨 Broadcast bhej diya. ✅ Sent: {sent} | ❌ Failed: {failed}")


@bot.on(events.NewMessage(pattern=r"^\.funkill$"))
async def fun_kill(event):
    global bot_alive
    if event.sender_id != OWNER_ID: return
    bot_alive = False
    await event.reply("🛑 Bot globally paused (owner only). `.funrevive` se wapas on karo.")


@bot.on(events.NewMessage(pattern=r"^\.funrevive$"))
async def fun_revive(event):
    global bot_alive
    if event.sender_id != OWNER_ID: return
    bot_alive = True
    await event.reply("✅ Bot wapas active ho gaya.")

# ────────────────────────────────────────────────
# 🔥 NEW FEATURE: ROAST LOOP (Auto Spam)
# ────────────────────────────────────────────────
async def roast_loop(chat_id: int):
    """Background task to send a roast message every 3 seconds."""
    try:
        while bot_alive:
            # Pura SPAM_ROAST_REPLIES me se random message chusega 
            msg = random.choice(SPAM_ROAST_REPLIES)
            await bot.send_message(chat_id, msg)
            await asyncio.sleep(3) # Har 3 second me bhejega
    except asyncio.CancelledError:
        pass # Loop ko gracefully band karne ke liye

@bot.on(events.NewMessage(pattern=r"^\.roast (on|off)$"))
async def toggle_roast_spam(event):
    """Command to start/stop the continuous roast loop in any chat."""
    # Sirf Bot Owner ye command use kar sakta hai
    if event.sender_id != OWNER_ID:
        return

    action = event.pattern_match.group(1).lower()
    chat_id = event.chat_id

    if action == "on":
        if chat_id in active_roasts:
            return await event.edit("🔥 Roast mode is chat me pehle se ON hai bhai!")
        
        await event.edit("🔥 **Roast Mode ON!** Ab dekh iska kya haal karta hoon... 🔥")
        
        # Background task create karo
        task = asyncio.create_task(roast_loop(chat_id))
        active_roasts[chat_id] = task

    elif action == "off":
        if chat_id in active_roasts:
            # Task ko cancel karo
            active_roasts[chat_id].cancel()
            del active_roasts[chat_id]
            await event.edit("🛑 **Roast Mode OFF!** Chalo maaf kiya isko.")
        else:
            await event.edit("ℹ️ Yahan koi roast chalu hi nahi tha bhai.")

# ────────────────────────────────────────────────
#   COMMANDS — info
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.funlist$"))
async def fun_list(event):
    if not event.is_group: return
    chat = get_chat(event.chat_id)
    if not chat["members"]: return await event.reply("ℹ️ Is group me abhi koi opt-in nahi hai.")
    lines = []
    for uid_str, info in chat["members"].items():
        lines.append(f"• (`{uid_str}`) — mood: {info.get('mood', 'chill')}")
    await event.reply("👥 **Opted-in members:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funstats$"))
async def fun_stats(event):
    if not event.is_group: return
    chat = get_chat(event.chat_id)
    if not chat["members"]: return await event.reply("ℹ️ Abhi koi data nahi hai.")
    ranked = sorted(chat["members"].items(), key=lambda kv: kv[1].get("reply_count", 0), reverse=True)
    lines = [f"• `{uid_str}` — {info.get('reply_count', 0)} replies" for uid_str, info in ranked[:10]]
    await event.reply("🏆 **Fun Leaderboard:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funaudit$"))
async def fun_audit(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    chat = get_chat(event.chat_id)
    if not chat["audit"]: return await event.reply("ℹ️ Abhi koi audit record nahi hai.")
    lines = [f"• `{r['user_id']}` — {r.get('joined_at')} to {r.get('left_at')}" for r in chat["audit"][-10:]]
    await event.reply("📜 **Recent opt-out audit:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.(?:funhelp|help)$"))
async def fun_help(event):
    text = (
        "🤖 **Fun Bot v2.4 — Complete Command Reference**\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**🔥 Special Tools (DM/Group)**\n"
        "😈 `.roast on/off` — Target ko continuously har 3s me roast karo (Spam mode)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**👤 Membership (Groups)**\n"
        "🎉 `.joinfun` — fun-mode me opt-in karo\n"
        "👋 `.leavefun` — opt-out karo\n"
        "🎛️ `.funtype hype|chill|roast` — apna reply-mood chuno\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**⚙️ Group Settings** _(admins only)_\n"
        "🔛 `.funmode on/off` — fun-mode enable/disable\n"
        "😀 `.funreact on/off` — group reactions on/off\n"
        "⏱️ `.funcooldown <seconds>` — set gap b/w replies (e.g. 5)\n"
        "🌙 `.funquiet <start> <end>` — sleep hours (e.g. 23:00 07:00)\n"
        "☀️ `.funquiet off` — quiet hours disable karo\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**🧵 Triggers (Custom Auto-Reply)**\n"
        "➕ `.trigger add <word> <reply>` — naya trigger lagao\n"
        "➖ `.trigger remove <word>` — trigger hatao\n"
        "📋 `.trigger list` — saare active triggers dekho\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**📊 Info & Logs**\n"
        "👥 `.funlist` — opted-in members ki list\n"
        "🏆 `.funstats` — sabse jyada reply paane wale log\n"
        "📜 `.funaudit` — recent opt-outs ki list\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**👑 Owner Controls**\n"
        "📢 `.funbroadcast <msg>` — saare members ko message bhejo\n"
        "🛑 `.funkill` — bot ko globally pause karo\n"
        "✅ `.funrevive` — bot ko wapas active karo\n"
    )
    await event.reply(text)


# ────────────────────────────────────────────────
#   AUTO FUN-REPLY (opt-in + rate-limited + mood + quiet hours)
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_fun(event):
    if not bot_alive or event.out or not event.is_group or is_sleeping():
        return

    # 🔥 NEW: Agar is chat me ROAST LOOP chal raha hai, to normal reply mat karo
    if event.chat_id in active_roasts:
        return

    text = event.raw_text or ""
    if text.startswith("."):
        return

    chat = get_chat(event.chat_id)
    if not chat["enabled"] or in_quiet_hours(chat):
        return

    uid = event.sender_id
    uid_str = str(uid)
    member = chat["members"].get(uid_str)
    if not member:
        return

    lowered = text.lower()
    trigger_hit = None
    for word, reply_text in chat["triggers"].items():
        if word in lowered:
            trigger_hit = reply_text
            break

    now = time.time()
    if now - last_reply_time.get(uid, 0) < chat.get("cooldown", DEFAULT_RATE_LIMIT_SECONDS):
        return
    last_reply_time[uid] = now

    try:
        await human_delay()
        reply_text_out = trigger_hit if trigger_hit else pick_reply(uid, member.get("mood", "chill"))
        await event.reply(reply_text_out)
        member["reply_count"] = member.get("reply_count", 0) + 1
        save_data()
    except FloodWaitError as fw:
        await asyncio.sleep(fw.seconds)
    except Exception:
        pass


# ────────────────────────────────────────────────
#   AUTO REACTION — ALL GROUP MESSAGES (no opt-in required)
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_react_group(event):
    if not bot_alive or event.out or not event.is_group or is_sleeping():
        return
    text = event.raw_text or ""
    if text.startswith("."):
        return

    chat = get_chat(event.chat_id)
    if not chat["enabled"] or not chat.get("react_enabled", True) or in_quiet_hours(chat):
        return

    uid = event.sender_id
    key = (event.chat_id, uid)
    now = time.time()
    if now - last_react_time.get(key, 0) < REACTION_ALL_COOLDOWN_SECONDS:
        return
    last_react_time[key] = now

    await send_real_reaction(event.chat_id, event.id)


# ────────────────────────────────────────────────
#   AUTO DM-REPLY
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_dm(event):
    if not bot_alive or event.out or not event.is_private or is_sleeping():
        return

    # 🔥 NEW: Agar is DM me ROAST LOOP chal raha hai, to normal reply mat karo
    if event.chat_id in active_roasts:
        return

    text = event.raw_text or ""
    if text.startswith("."):
        return

    uid = event.sender_id
    now = time.time()
    if now - last_dm_reply_time.get(uid, 0) < DM_RATE_LIMIT_SECONDS:
        return
    last_dm_reply_time[uid] = now

    try:
        reply = pick_dm_reply(uid, text)
        await event.reply(reply)
        await send_real_reaction(event.chat_id, event.id)
    except FloodWaitError as fw:
        await asyncio.sleep(fw.seconds)
    except Exception:
        pass


# ────────────────────────────────────────────────
#   SETTINGS HOT-RELOAD
# ────────────────────────────────────────────────
async def settings_watcher():
    global DEFAULT_RATE_LIMIT_SECONDS, HUMAN_MODE, SLEEP_START, SLEEP_END
    was_sleeping = False
    while True:
        try:
            if os.path.isfile(SETTINGS_FILE):
                with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
                    s = json.load(f)
                if "default_cooldown" in s:
                    DEFAULT_RATE_LIMIT_SECONDS = int(s["default_cooldown"])
                if "react_enabled_global" in s and not s["react_enabled_global"]:
                    for chat in data.values():
                        chat["react_enabled"] = False
                    save_data()
                if "human_mode" in s:
                    HUMAN_MODE = bool(s["human_mode"])
                if "sleep_start" in s:
                    SLEEP_START = s["sleep_start"]
                if "sleep_end" in s:
                    SLEEP_END = s["sleep_end"]
        except Exception:
            pass
        await asyncio.sleep(20)


# ────────────────────────────────────────────────
#   START
# ────────────────────────────────────────────────
async def login_only():
    await bot.start()
    _save_string_session(bot.session.save())
    me = await bot.get_me()
    print(f"✅ Login successful — logged in as {me.first_name} (@{me.username}).")
    await bot.disconnect()


async def main():
    await bot.start()
    _save_string_session(bot.session.save())
    me = await bot.get_me()
    log.info("🤖 FUN BOT v2.4 STARTED (With 55+ Messages Roast Loop & Full Help Menu)")
    log.info(f"👤 Logged in as → {me.first_name}")
    asyncio.create_task(settings_watcher())
    await bot.run_until_disconnected()


if __name__ == "__main__":
    if ARGS.login_only:
        asyncio.run(login_only())
    else:
        asyncio.run(main())

