# ────────────────────────────────────────────────
#   OPT-IN GROUP FUN BOT v2.4 (Telethon Userbot)
#   Text replies remain opt-in/consent-based. Reactions
#   in groups are NOT consent-gated (see v2.4 note below) —
#   this raises automation-detection / ban risk, use with care.
#
#   CHANGES IN v2.4:
#   - Group reactions ab SABHI messages pe chalti hain, opt-in
#     ki zaroorat nahi (pehle sirf opted-in members ke messages
#     pe reaction milti thi). Text-reply abhi bhi sirf opted-in
#     members ke liye hai — sirf reaction ka scope badla hai.
#   - Reaction ka apna alag per-user cooldown hai (chat ke
#     `.funcooldown` wahi cooldown reuse karta hai) taaki har
#     single message pe reaction dene se flood/ban risk na badhe.
#   - `.funreact on/off` ab is naye "react-to-everyone" behaviour
#     ko bhi control karta hai.
#
#   CHANGES IN v2.3:
#   - Bot ab HAR reply pe TEXT + REAL Telegram REACTION
#     dono ek saath deta hai — group aur DM, dono jagah,
#     hamesha (pehle wala 25% random "bonus" hata diya)
#   - Reaction ab asli Telegram reaction hai (SendReactionRequest
#     se), pehle wo sirf ek extra text message tha jo dikhta
#     reaction jaisa tha lekin actually reaction nahi tha
#   - `.funreact on/off` command ab kaam karta hai (pehle sirf
#     changelog me likha tha, code me implement nahi tha)
#   - DMs me reactions hamesha allowed hain (jaisa comment me
#     pehle se likha tha)
#
#   CHANGES IN v2.2:
#   - Bot ab HAR baar TEXT reply + emoji REACTION dono
#     ek saath deta hai — group aur DM, dono jagah
#   - New admin command `.funreact on/off` to toggle
#     reactions per group (DMs always allowed to react)
#
#   CHANGES IN v2.1:
#   - All auto-replies trimmed to 2-4 words (short & punchy)
#   - Fixed opt-out bug: leaving now saves the member's
#     history to an audit log BEFORE deleting the active
#     record, instead of losing it
#   - Everything else from v2 kept (cooldowns, quiet hours,
#     triggers, moods, broadcast, export, kill-switch, etc.)
#
#   NOTE: This is a userbot (runs on a personal account via
#   Telethon), not a Bot API bot. Automating a personal
#   Telegram account like this can conflict with Telegram's
#   Terms of Service (which restrict bulk/automated messaging
#   from user accounts) and can get the account limited or
#   banned, regardless of how consent-based the feature is.
#   Worth keeping in mind before running this on a real account.
# ────────────────────────────────────────────────

import argparse
import asyncio
import json
import logging
import os
import random
import re
import sys
import time
from datetime import datetime, time as dtime
from pathlib import Path
from typing import Dict, List, Optional

from telethon import TelegramClient, events
from telethon.errors import FloodWaitError, RPCError
from telethon.sessions import StringSession
from telethon.tl.functions.messages import SendReactionRequest
from telethon.tl.types import ReactionEmoji

# ────────────────────────────────────────────────
#   CONFIG — loaded from a per-clone JSON file, NOT hardcoded.
#   Run with: python funbot_core.py --config /path/to/config.json
#   The config.json is generated by factory_bot.py and looks like:
#   {
#     "api_id": 12345678,
#     "api_hash": "...",
#     "owner_id": 123456789,
#     "session_file": "/path/to/funbot_session.txt",
#     "data_file": "/path/to/funbot_data.json"
#   }
#
#   --login-only : connects, runs Telethon's normal interactive phone/OTP
#   prompt directly in THIS terminal (never through any bot chat), saves
#   the resulting session string, then exits without starting the event
#   handlers. Use this once per clone to complete login yourself.
# ────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Fun Bot clone (per-user config)")
parser.add_argument("--config", required=True, help="Path to this clone's config.json")
parser.add_argument("--login-only", action="store_true",
                     help="Only perform interactive login and save the session, then exit")
ARGS = parser.parse_args()

CONFIG_PATH = Path(ARGS.config).resolve()
if not CONFIG_PATH.is_file():
    print(f"❌ Config file not found: {CONFIG_PATH}")
    sys.exit(1)

with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    _cfg = json.load(f)

API_ID = int(_cfg["api_id"])
API_HASH = str(_cfg["api_hash"])
OWNER_ID = int(_cfg["owner_id"])
SESSION_FILE = _cfg.get("session_file", str(CONFIG_PATH.parent / "funbot_session.txt"))
DATA_FILE = _cfg.get("data_file", str(CONFIG_PATH.parent / "funbot_data.json"))
SETTINGS_FILE = _cfg.get("settings_file", str(CONFIG_PATH.parent / "settings.json"))
LOG_FILE = _cfg.get("log_file", str(CONFIG_PATH.parent / "funbot.log"))

# Optional MongoDB sync (feature 9) — set by factory_bot.py in config.json.
# If empty, this clone just uses the local SESSION_FILE, same as before.
MONGODB_URI = _cfg.get("mongodb_uri", "")
MONGODB_DB_NAME = _cfg.get("mongodb_db_name", "funbot_factory")
MONGO_OWNER_KEY = _cfg.get("factory_owner_telegram_id", OWNER_ID)

DEFAULT_RATE_LIMIT_SECONDS = 3       # default min gap between fun-replies to same user
DM_RATE_LIMIT_SECONDS = 3            # min gap between auto-replies to same DM sender

# ────────────────────────────────────────────────
#   LOGGING
# ────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    handlers=[logging.FileHandler(LOG_FILE, encoding="utf-8"), logging.StreamHandler()],
)
log = logging.getLogger("funbot")

# ────────────────────────────────────────────────
#   REPLY BANKS (mood-based, all replies 2-4 words)
# ────────────────────────────────────────────────
HYPE_REPLIES = [
    "🔥 Full energy bhai",
    "🎉 Party mode on",
    "🥳 Vibes are lit",
    "💯 Pure facts yaar",
    "🚀 Upar hi upar",
    "⚡ Full power on",
    "🏆 Champion move bhai",
    "🎯 Bullseye energy hai",
    "🎊 Confetti time now",
    "🌟 Star player alert",
    "🔊 Volume up bhai",
    "🥇 Gold medal reply",
    "🕺 Naach uth gaya",
    "🎆 Fireworks incoming bhai",
    "🚨 Too much swag",
]

CHILL_REPLIES = [
    "😂 Haha nice one",
    "🤝 Squad approved bhai",
    "😎 Cool cool cool",
    "😅 Sunna hi padega",
    "🙂 Sahi hai bhai",
    "☕ Chai pe charcha",
    "🌤️ Halka phulka vibe",
    "🧘 Shaant sukoon wali",
    "🍃 Aaram se bhai",
    "😌 Bilkul theek laga",
    "🎈 Simple sweet solid",
    "🪁 Udta hua mood",
    "🛋️ Comfy vibes only",
    "🌙 Chill raho bhai",
    "😊 Accha laga padhke",
]

ROAST_REPLIES = [
    "😏 Wah kya baat",
    "🙃 Ye bhi koi baat",
    "😬 Thoda aur try",
    "🤨 Interesting take bhai",
    "😂 Bhai tu bhi",
    "🫣 Seedha nahi tha",
    "😜 Maan liya chalo",
    "🥲 Kabhi kabhi hota hai",
    "😅 Full drama bhai",
    "🤡 Full comedy hai",
    "🙈 Sab dekh rahe",
    "😹 Bas bas yaar",
    "🫡 Salute is confidence",
    "😌 Chalta hai yaar",
    "🎭 Drama series ban sakta",
]

NEUTRAL_REPLIES = [
    "👍 Noted bhai",
    "✅ Theek hai bhai",
    "🙌 Squad approved",
    "🤗 Accha laga",
    "💬 Baat sahi hai",
    "📌 Yaad rakha jayega",
    "🎶 Sunte rehna isse",
    "🧩 Fit baith gaya",
]

MOOD_BANKS = {
    "hype": HYPE_REPLIES,
    "chill": CHILL_REPLIES,
    "roast": ROAST_REPLIES,
}

ALL_REPLIES = HYPE_REPLIES + CHILL_REPLIES + ROAST_REPLIES + NEUTRAL_REPLIES

DM_REPLIES = [
    "👋 Thoda busy hoon",
    "😊 Jald reply karunga",
    "🙌 Baat karta hoon",
    "📩 Reply aa raha",
    "⏳ Wapas aata hoon",
    "🙏 Reply jald aayega",
    "🕐 Thoda wait karo",
    "📨 Jald baat karte",
    "😴 Away hoon abhi",
    "🚶 Jald milta hoon",
    "✋ Dekh raha hoon",
    "🔔 Jaldi reply karunga",
    "📲 Baat karte hain",
    "🙋 Jald reply aayega",
    "🧘 Jald connect karta",
]

# ── Keyword → context-aware DM reply banks (all 2-4 words) ──
DM_GREETING_TRIGGERS = ["hi", "hii", "hiii", "hello", "hey", "namaste", "namaskar", "yo"]
DM_GREETING_REPLIES = [
    "👋 Hey kaise ho",
    "😊 Bolo kya haal",
    "🙌 Hii sab badhiya",
    "😄 Kya chal raha",
]

DM_HOWAREYOU_TRIGGERS = ["how are you", "kaise ho", "kaisi ho", "kya haal", "kya hal", "sab theek"]
DM_HOWAREYOU_REPLIES = [
    "😊 Badhiya hoon aap",
    "🙌 Sab set hai",
    "😎 Mast hoon bhai",
]

DM_THANKS_TRIGGERS = ["thanks", "thank you", "thnx", "tysm", "shukriya", "dhanyawad"]
DM_THANKS_REPLIES = [
    "🙏 Koi baat nahi",
    "😊 Welcome welcome bhai",
    "🤝 Anytime yaar",
    "💯 Always here bhai",
]

DM_BYE_TRIGGERS = ["bye", "gtg", "good night", "goodnight", "chalta hoon", "milte hai", "milte hain", "tata"]
DM_BYE_REPLIES = [
    "👋 Bye take care",
    "😴 Good night bhai",
    "🙌 Baad me baat",
    "✌️ See you soon",
]

DM_QUESTION_TRIGGERS = ["?", "kya", "kaise", "kyu", "kyun", "kab", "kahan", "kaun"]
DM_QUESTION_REPLIES = [
    "🤔 Accha sawal hai",
    "📝 Jald reply karunga",
    "🧐 Jald batata hoon",
]

DM_LOVE_TRIGGERS = ["love you", "miss you", "pyaar", "ilu"]
DM_LOVE_REPLIES = [
    "🥰 Aww that's sweet",
    "❤️ Accha laga sunke",
    "🤗 Same here bhai",
]

DM_ANGRY_TRIGGERS = ["gussa", "angry", "naraz", "irritat", "pareshan"]
DM_ANGRY_REPLIES = [
    "😟 Sab theek na",
    "🫂 Calm ho jao",
    "💬 Batao kya baat",
]

# Ordered so more specific/emotional intents are checked before generic ones
DM_INTENT_BANKS = [
    (DM_ANGRY_TRIGGERS, DM_ANGRY_REPLIES),
    (DM_LOVE_TRIGGERS, DM_LOVE_REPLIES),
    (DM_THANKS_TRIGGERS, DM_THANKS_REPLIES),
    (DM_BYE_TRIGGERS, DM_BYE_REPLIES),
    (DM_HOWAREYOU_TRIGGERS, DM_HOWAREYOU_REPLIES),
    (DM_GREETING_TRIGGERS, DM_GREETING_REPLIES),
    (DM_QUESTION_TRIGGERS, DM_QUESTION_REPLIES),
]


def _trigger_matches(text_lower: str, words: set, trigger: str) -> bool:
    """Whole-word match for single-word triggers (so 'hi' doesn't match inside
    'nahi'/'abhi'/'sahi'); substring match only for multi-word phrases and
    punctuation-only triggers like '?'."""
    if trigger == "?":
        return "?" in text_lower
    if " " in trigger:
        return trigger in text_lower
    return trigger in words


def pick_dm_reply(uid: int, text: str) -> str:
    """Context-aware DM reply: checks message content against intent keyword
    banks first (greeting, thanks, bye, question, etc.), falls back to the
    generic DM_REPLIES pool if nothing matches. Avoids immediate repeats."""
    lowered = (text or "").lower()
    words = set(re.findall(r"[a-z]+", lowered))  # whole-word tokens only

    bank = DM_REPLIES
    for triggers, replies in DM_INTENT_BANKS:
        if any(_trigger_matches(lowered, words, t) for t in triggers):
            bank = replies
            break

    reply = random.choice(bank)
    tries = 0
    while reply == last_dm_reply_text.get(uid) and tries < 5 and len(bank) > 1:
        reply = random.choice(bank)
        tries += 1
    last_dm_reply_text[uid] = reply
    return reply

REACTION_EMOJIS = ["👍", "🔥", "😂", "❤️", "🎉", "👏", "😎", "💯"]

# ────────────────────────────────────────────────
#   STORAGE (per-group, JSON)
#   structure:
#   {
#     "<chat_id>": {
#        "enabled": bool,
#        "cooldown": int,
#        "quiet_start": "HH:MM" | null,
#        "quiet_end": "HH:MM" | null,
#        "triggers": {"word": "reply text"},
#        "react_enabled": bool,
#        "members": {
#            "<user_id>": {
#                "mood": "hype"|"chill"|"roast"|"neutral",
#                "joined_at": iso_ts,
#                "reply_count": int
#            }
#        },
#        "audit": [
#            {"user_id": "...", "joined_at": iso_ts, "left_at": iso_ts,
#             "reply_count": int}
#        ]
#     }
#   }
# ────────────────────────────────────────────────
data: Dict[str, dict] = {}
last_reply_time: Dict[int, float] = {}
last_dm_reply_time: Dict[int, float] = {}
last_reply_text: Dict[int, str] = {}   # avoid immediate repeats per user (groups)
last_dm_reply_text: Dict[int, str] = {}  # avoid immediate repeats per user (DMs)
last_react_time: Dict[tuple, float] = {}  # (chat_id, user_id) -> ts, flood-protection for all-message reactions
REACTION_ALL_COOLDOWN_SECONDS = 3      # light per-user cooldown so reactions don't flood-wait on rapid messages
bot_alive = True                        # global kill-switch state


def load_data():
    global data
    try:
        if os.path.isfile(DATA_FILE):
            with open(DATA_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
        else:
            data = {}
    except Exception as e:
        log.error(f"Load error: {e}")
        data = {}


def save_data():
    try:
        with open(DATA_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        log.error(f"Save error: {e}")


def get_chat(chat_id: int) -> dict:
    key = str(chat_id)
    if key not in data:
        data[key] = {
            "enabled": False,
            "cooldown": DEFAULT_RATE_LIMIT_SECONDS,
            "quiet_start": None,
            "quiet_end": None,
            "triggers": {},
            "members": {},
            "audit": [],
            "react_enabled": True,
        }
    # backfill for old-format files
    chat = data[key]
    chat.setdefault("cooldown", DEFAULT_RATE_LIMIT_SECONDS)
    chat.setdefault("quiet_start", None)
    chat.setdefault("quiet_end", None)
    chat.setdefault("triggers", {})
    chat.setdefault("members", {})
    chat.setdefault("audit", [])
    chat.setdefault("react_enabled", True)
    return chat


load_data()

def _load_string_session() -> str:
    """Reads the saved session string from SESSION_FILE if it exists, else
    returns an empty string (Telethon will prompt for phone/OTP login and
    we'll save the resulting session string after connecting)."""
    if os.path.isfile(SESSION_FILE):
        try:
            with open(SESSION_FILE, "r", encoding="utf-8") as f:
                return f.read().strip()
        except Exception as e:
            log.error(f"Could not read {SESSION_FILE}: {e}")
    return ""


def _save_string_session(session_str: str):
    try:
        with open(SESSION_FILE, "w", encoding="utf-8") as f:
            f.write(session_str)
        os.chmod(SESSION_FILE, 0o600)  # keep the session string private
    except Exception as e:
        log.error(f"Could not save {SESSION_FILE}: {e}")

    # Mirror the session string to MongoDB too, so factory_bot.py can
    # rebuild this file on a fresh container (feature 9). Non-fatal if it
    # fails — the local file above is still the source of truth for THIS run.
    if MONGODB_URI:
        try:
            from pymongo import MongoClient
            client = MongoClient(MONGODB_URI, serverSelectionTimeoutMS=5000)
            client[MONGODB_DB_NAME]["clones"].update_one(
                {"owner_id": MONGO_OWNER_KEY},
                {"$set": {"session_string": session_str}},
                upsert=True,
            )
            client.close()
            log.info("Session string synced to MongoDB.")
        except Exception as e:
            log.warning(f"MongoDB session sync failed (non-fatal, local file still saved): {e}")


bot = TelegramClient(StringSession(_load_string_session()), API_ID, API_HASH, auto_reconnect=True)


# ────────────────────────────────────────────────
#   HELPERS
# ────────────────────────────────────────────────
async def is_group_admin(event) -> bool:
    if event.sender_id == OWNER_ID:
        return True
    try:
        perms = await bot.get_permissions(event.chat_id, event.sender_id)
        return bool(perms.is_admin or perms.is_creator)
    except Exception:
        return False


def in_quiet_hours(chat: dict) -> bool:
    """Returns True if current local time falls inside the group's quiet window."""
    start_s, end_s = chat.get("quiet_start"), chat.get("quiet_end")
    if not start_s or not end_s:
        return False
    try:
        now = datetime.now().time()
        start = dtime.fromisoformat(start_s)
        end = dtime.fromisoformat(end_s)
        if start <= end:
            return start <= now <= end
        # window wraps past midnight, e.g. 23:00 -> 06:00
        return now >= start or now <= end
    except Exception:
        return False


def pick_reply(uid: int, mood: str) -> str:
    bank = MOOD_BANKS.get(mood, ALL_REPLIES)
    reply = random.choice(bank)
    # avoid immediate repeat if possible
    tries = 0
    while reply == last_reply_text.get(uid) and tries < 5 and len(bank) > 1:
        reply = random.choice(bank)
        tries += 1
    last_reply_text[uid] = reply
    return reply


def parse_hhmm(s: str) -> Optional[str]:
    try:
        h, m = s.split(":")
        h, m = int(h), int(m)
        if 0 <= h <= 23 and 0 <= m <= 59:
            return f"{h:02d}:{m:02d}"
    except Exception:
        pass
    return None


async def send_real_reaction(chat_id: int, msg_id: int, emoji: Optional[str] = None):
    """Sends an actual Telegram reaction (the small emoji popup on the message
    corner) using SendReactionRequest — NOT a text message. Separate from the
    normal text reply. Fails silently (logged) since a reaction failing should
    never block the text reply from having already been sent."""
    chosen = emoji or random.choice(REACTION_EMOJIS)
    try:
        await bot(SendReactionRequest(
            peer=chat_id,
            msg_id=msg_id,
            reaction=[ReactionEmoji(emoticon=chosen)],
        ))
    except FloodWaitError as fw:
        log.warning(f"Flood wait on reaction: {fw.seconds}s")
        await asyncio.sleep(fw.seconds)
    except RPCError as e:
        log.warning(f"Reaction RPC error (emoji may be unsupported in this chat): {e}")
    except Exception as e:
        log.warning(f"Reaction failed: {e}")


# ────────────────────────────────────────────────
#   COMMANDS — membership
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.joinfun$"))
async def join_fun(event):
    if not event.is_group:
        return await event.reply("⚠️ Ye command sirf group me chalta hai.")

    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)

    if uid in chat["members"]:
        return await event.reply("✅ Aap already opted-in ho.")

    chat["members"][uid] = {
        "mood": "chill",
        "joined_at": datetime.now().isoformat(timespec="seconds"),
        "reply_count": 0,
    }
    save_data()
    log.info(f"User {uid} joined fun in chat {event.chat_id}")
    await event.reply(
        "🎉 Aap fun-mode me opt-in ho gaye! Bahar aane ke liye `.leavefun` bhejo.\n"
        "Mood set karne ke liye: `.funtype hype|chill|roast`"
    )


@bot.on(events.NewMessage(pattern=r"^\.leavefun$"))
async def leave_fun(event):
    if not event.is_group:
        return

    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)

    member = chat["members"].get(uid)
    if not member:
        return await event.reply("ℹ️ Aap opted-in nahi the.")

    # Save the member's history to the audit log BEFORE removing them,
    # so opt-in/opt-out history isn't lost (fixes v2 bug where the
    # record was deleted right after left_at was set).
    chat["audit"].append({
        "user_id": uid,
        "joined_at": member.get("joined_at"),
        "left_at": datetime.now().isoformat(timespec="seconds"),
        "reply_count": member.get("reply_count", 0),
    })
    del chat["members"][uid]
    save_data()
    log.info(f"User {uid} left fun in chat {event.chat_id}")
    await event.reply("👋 Aap fun-mode se bahar ho gaye.")


@bot.on(events.NewMessage(pattern=r"^\.funtype (hype|chill|roast)$"))
async def set_mood(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)
    if uid not in chat["members"]:
        return await event.reply("⚠️ Pehle `.joinfun` karo.")
    mood = event.pattern_match.group(1)
    chat["members"][uid]["mood"] = mood
    save_data()
    await event.reply(f"🎛️ Aapka fun-mood set ho gaya: **{mood}**")


# ────────────────────────────────────────────────
#   COMMANDS — admin controls
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.funmode (on|off)$"))
async def fun_mode_toggle(event):
    if not event.is_group:
        return await event.reply("⚠️ Ye command sirf group me chalta hai.")
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")

    state = event.pattern_match.group(1) == "on"
    chat = get_chat(event.chat_id)
    chat["enabled"] = state
    save_data()
    log.info(f"Fun mode {'enabled' if state else 'disabled'} in chat {event.chat_id}")
    await event.reply(f"⚙️ Fun-mode is group ke liye **{'ON' if state else 'OFF'}** kar diya gaya.")


@bot.on(events.NewMessage(pattern=r"^\.funreact (on|off)$"))
async def fun_react_toggle(event):
    """Toggles whether the bot adds a real Telegram reaction alongside its
    text reply, for this group specifically. DMs always react regardless."""
    if not event.is_group:
        return await event.reply("⚠️ Ye command sirf group me chalta hai.")
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")

    state = event.pattern_match.group(1) == "on"
    chat = get_chat(event.chat_id)
    chat["react_enabled"] = state
    save_data()
    log.info(f"Reactions {'enabled' if state else 'disabled'} in chat {event.chat_id}")
    await event.reply(f"😀 Reactions is group ke liye **{'ON' if state else 'OFF'}** kar di gayi.")


@bot.on(events.NewMessage(pattern=r"^\.funcooldown (\d+)$"))
async def set_cooldown(event):
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")
    seconds = int(event.pattern_match.group(1))
    seconds = max(5, min(seconds, 3600))
    chat = get_chat(event.chat_id)
    chat["cooldown"] = seconds
    save_data()
    await event.reply(f"⏱️ Cooldown set ho gaya: **{seconds}s** per user.")


@bot.on(events.NewMessage(pattern=r"^\.funquiet (\d{1,2}:\d{2}) (\d{1,2}:\d{2})$"))
async def set_quiet_hours(event):
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")
    start = parse_hhmm(event.pattern_match.group(1))
    end = parse_hhmm(event.pattern_match.group(2))
    if not start or not end:
        return await event.reply("⚠️ Format: `.funquiet 23:00 07:00`")
    chat = get_chat(event.chat_id)
    chat["quiet_start"] = start
    chat["quiet_end"] = end
    save_data()
    await event.reply(f"🌙 Quiet hours set: **{start} → {end}** (is window me auto-reply nahi aayega).")


@bot.on(events.NewMessage(pattern=r"^\.funquiet off$"))
async def clear_quiet_hours(event):
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")
    chat = get_chat(event.chat_id)
    chat["quiet_start"] = None
    chat["quiet_end"] = None
    save_data()
    await event.reply("☀️ Quiet hours hata diye gaye.")


@bot.on(events.NewMessage(pattern=r"^\.trigger add (\S+) (.+)$"))
async def trigger_add(event):
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")
    word = event.pattern_match.group(1).lower()
    reply_text = event.pattern_match.group(2)
    chat = get_chat(event.chat_id)
    chat["triggers"][word] = reply_text
    save_data()
    await event.reply(f"➕ Trigger add ho gaya: `{word}` → {reply_text}")


@bot.on(events.NewMessage(pattern=r"^\.trigger remove (\S+)$"))
async def trigger_remove(event):
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")
    word = event.pattern_match.group(1).lower()
    chat = get_chat(event.chat_id)
    if word in chat["triggers"]:
        del chat["triggers"][word]
        save_data()
        await event.reply(f"➖ Trigger hata diya: `{word}`")
    else:
        await event.reply("ℹ️ Ye trigger exist nahi karta.")


@bot.on(events.NewMessage(pattern=r"^\.trigger list$"))
async def trigger_list(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    if not chat["triggers"]:
        return await event.reply("ℹ️ Koi trigger set nahi hai.")
    lines = [f"• `{w}` → {r}" for w, r in chat["triggers"].items()]
    await event.reply("🧵 **Active Triggers:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funbroadcast (.+)$"))
async def fun_broadcast(event):
    """Admin-only: send a message to every opted-in member's DM (still consent-based, since
    only users who already opted into this specific group's fun-mode are targeted)."""
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")

    msg = event.pattern_match.group(1)
    chat = get_chat(event.chat_id)
    if not chat["members"]:
        return await event.reply("ℹ️ Koi opted-in member nahi hai.")

    sent, failed = 0, 0
    for uid_str in list(chat["members"].keys()):
        try:
            await bot.send_message(int(uid_str), f"📢 **Fun Bot Announcement:**\n{msg}")
            sent += 1
            await asyncio.sleep(1)  # gentle pacing to avoid flood limits
        except Exception as e:
            failed += 1
            log.warning(f"Broadcast failed for {uid_str}: {e}")

    await event.reply(f"📨 Broadcast bhej diya. ✅ Sent: {sent} | ❌ Failed: {failed}")


@bot.on(events.NewMessage(pattern=r"^\.funkill$"))
async def fun_kill(event):
    global bot_alive
    if event.sender_id != OWNER_ID:
        return
    bot_alive = False
    log.warning("Bot globally disabled by owner")
    await event.reply("🛑 Bot globally paused (owner only). `.funrevive` se wapas on karo.")


@bot.on(events.NewMessage(pattern=r"^\.funrevive$"))
async def fun_revive(event):
    global bot_alive
    if event.sender_id != OWNER_ID:
        return
    bot_alive = True
    log.info("Bot globally re-enabled by owner")
    await event.reply("✅ Bot wapas active ho gaya.")


@bot.on(events.NewMessage(pattern=r"^\.funexport$"))
async def fun_export(event):
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")
    chat = get_chat(event.chat_id)
    export_name = f"funbot_export_{event.chat_id}.json"
    with open(export_name, "w", encoding="utf-8") as f:
        json.dump(chat, f, indent=2, ensure_ascii=False)
    await event.reply(file=export_name, message="📦 Is group ka fun-data export.")
    try:
        os.remove(export_name)
    except Exception:
        pass


# ────────────────────────────────────────────────
#   COMMANDS — info
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.funlist$"))
async def fun_list(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    if not chat["members"]:
        return await event.reply("ℹ️ Is group me abhi koi opt-in nahi hai.")

    lines = []
    for uid_str, info in chat["members"].items():
        try:
            user = await bot.get_entity(int(uid_str))
            name = user.first_name or uid_str
        except Exception:
            name = uid_str
        lines.append(f"• {name} (`{uid_str}`) — mood: {info.get('mood', 'chill')}")

    await event.reply("👥 **Opted-in members:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funstats$"))
async def fun_stats(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    if not chat["members"]:
        return await event.reply("ℹ️ Abhi koi data nahi hai.")

    ranked = sorted(chat["members"].items(), key=lambda kv: kv[1].get("reply_count", 0), reverse=True)
    lines = []
    medals = ["🥇", "🥈", "🥉"]
    for i, (uid_str, info) in enumerate(ranked[:10]):
        try:
            user = await bot.get_entity(int(uid_str))
            name = user.first_name or uid_str
        except Exception:
            name = uid_str
        prefix = medals[i] if i < 3 else f"{i + 1}."
        lines.append(f"{prefix} {name} — {info.get('reply_count', 0)} replies")

    await event.reply("🏆 **Fun Leaderboard:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funaudit$"))
async def fun_audit(event):
    """Shows the last 10 opt-in/opt-out records for this group (admins only)."""
    if not event.is_group:
        return
    if not await is_group_admin(event):
        return await event.reply("❌ Sirf group admins ye command chala sakte hain.")
    chat = get_chat(event.chat_id)
    if not chat["audit"]:
        return await event.reply("ℹ️ Abhi koi audit record nahi hai.")
    lines = []
    for rec in chat["audit"][-10:]:
        lines.append(
            f"• `{rec['user_id']}` — joined {rec.get('joined_at', '?')}, "
            f"left {rec.get('left_at', '?')}, replies {rec.get('reply_count', 0)}"
        )
    await event.reply("📜 **Recent opt-out audit:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.(?:funhelp|help)$"))
async def fun_help(event):
    text = (
        "🤖 **Fun Bot v2.4 — Command Reference**\n"
        "`.help` / `.funhelp` — ye list, koi bhi chala sakta hai\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "\n"
        "**👤 Membership**\n"
        "🎉 `.joinfun` — fun-mode me opt-in karo\n"
        "👋 `.leavefun` — opt-out karo\n"
        "🎛️ `.funtype hype|chill|roast` — apna reply-mood chuno\n"
        "\n"
        "**📊 Info**\n"
        "👥 `.funlist` — opted-in members dekho\n"
        "🏆 `.funstats` — leaderboard dekho\n"
        "🧵 `.trigger list` — active keyword-triggers dekho\n"
        "\n"
        "**⚙️ Group Settings** _(admins only)_\n"
        "🔛 `.funmode on/off` — fun-mode enable/disable\n"
        "😀 `.funreact on/off` — group reactions on/off\n"
        "⏱️ `.funcooldown <sec>` — reply cooldown set karo\n"
        "🌙 `.funquiet HH:MM HH:MM` — quiet hours set karo\n"
        "☀️ `.funquiet off` — quiet hours hatao\n"
        "\n"
        "**🧵 Triggers** _(admins only)_\n"
        "➕ `.trigger add <word> <reply>` — naya trigger banao\n"
        "➖ `.trigger remove <word>` — trigger hatao\n"
        "\n"
        "**🛠️ Admin Tools** _(admins only)_\n"
        "📢 `.funbroadcast <msg>` — opted-in members ko DM bhejo\n"
        "📦 `.funexport` — group ka data JSON export karo\n"
        "📜 `.funaudit` — opt-in/opt-out history dekho\n"
        "\n"
        "**👑 Owner Controls**\n"
        "🛑 `.funkill` — bot ko globally pause karo\n"
        "✅ `.funrevive` — bot ko wapas active karo\n"
        "\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "💬 **Text reply** — sirf opted-in members (group), sabko (DM)\n"
        "😀 **Reaction** — group ke har message pe (opt-in zaroori nahi), "
        "`.funreact off` se band\n"
        "✂️ Auto-replies short hain (2-4 words); DM me context ke hisaab se "
        "reply aata hai"
    )
    await event.reply(text)


# ────────────────────────────────────────────────
#   AUTO FUN-REPLY (opt-in + rate-limited + mood + quiet hours)
#   Now always sends TEXT reply + REAL reaction together (subject to
#   the group's react_enabled toggle).
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_fun(event):
    if not bot_alive:
        return
    if event.out:
        return
    if not event.is_group:
        return

    text = event.raw_text or ""
    if text.startswith("."):
        return  # don't reply to commands

    chat = get_chat(event.chat_id)
    if not chat["enabled"]:
        return
    if in_quiet_hours(chat):
        return

    uid = event.sender_id
    uid_str = str(uid)
    member = chat["members"].get(uid_str)
    if not member:
        return

    # keyword triggers take priority over generic mood replies
    lowered = text.lower()
    trigger_hit = None
    for word, reply_text in chat["triggers"].items():
        if word in lowered:
            trigger_hit = reply_text
            break

    cooldown = chat.get("cooldown", DEFAULT_RATE_LIMIT_SECONDS)
    now = time.time()
    if now - last_reply_time.get(uid, 0) < cooldown:
        return
    last_reply_time[uid] = now

    try:
        reply_text_out = trigger_hit if trigger_hit else pick_reply(uid, member.get("mood", "chill"))
        await event.reply(reply_text_out)
        # NOTE: reaction is handled separately by auto_react_group below,
        # which now reacts to every message in the group (not just
        # opted-in members' messages), so we don't react here too.

        member["reply_count"] = member.get("reply_count", 0) + 1
        save_data()
    except FloodWaitError as fw:
        log.warning(f"Flood wait {fw.seconds}s")
        await asyncio.sleep(fw.seconds)
    except RPCError as e:
        log.error(f"RPC error in auto_fun: {e}")
    except Exception as e:
        log.error(f"Unexpected error in auto_fun: {e}")


# ────────────────────────────────────────────────
#   AUTO REACTION — ALL GROUP MESSAGES (no opt-in required)
#   Fires for every non-command message in a fun-mode-enabled group,
#   regardless of whether the sender opted in with .joinfun. Text
#   auto-replies above stay opt-in gated; this reacts to everyone.
#   Toggle per group with `.funreact on/off`.
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_react_group(event):
    if not bot_alive:
        return
    if event.out:
        return
    if not event.is_group:
        return

    text = event.raw_text or ""
    if text.startswith("."):
        return  # don't react to commands

    chat = get_chat(event.chat_id)
    if not chat["enabled"]:
        return
    if not chat.get("react_enabled", True):
        return
    if in_quiet_hours(chat):
        return

    uid = event.sender_id
    key = (event.chat_id, uid)
    now = time.time()
    if now - last_react_time.get(key, 0) < REACTION_ALL_COOLDOWN_SECONDS:
        return
    last_react_time[key] = now

    await send_real_reaction(event.chat_id, event.id)


# ────────────────────────────────────────────────
#   AUTO DM-REPLY (consent implicit: only replies to messages sent to you directly)
#   Now always sends TEXT reply + REAL reaction together. Reactions are
#   always allowed in DMs regardless of any group setting.
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_dm(event):
    if not bot_alive:
        return
    if event.out:
        return
    if not event.is_private:
        return

    text = event.raw_text or ""
    if text.startswith("."):
        return

    uid = event.sender_id
    now = time.time()
    if now - last_dm_reply_time.get(uid, 0) < DM_RATE_LIMIT_SECONDS:
        return
    last_dm_reply_time[uid] = now

    try:
        reply = pick_dm_reply(uid, text)
        await event.reply(reply)

        # real Telegram reaction on the user's DM, always on
        await send_real_reaction(event.chat_id, event.id)
    except FloodWaitError as fw:
        await asyncio.sleep(fw.seconds)
    except RPCError as e:
        log.error(f"RPC error in auto_dm: {e}")
    except Exception as e:
        log.error(f"Unexpected error in auto_dm: {e}")


# ────────────────────────────────────────────────
#   SETTINGS HOT-RELOAD
#   factory_bot.py writes to SETTINGS_FILE when the owner changes
#   something from the "My Clone Settings" menu. This clone polls it
#   every 20s and applies the values live — no restart needed.
# ────────────────────────────────────────────────
async def settings_watcher():
    global DEFAULT_RATE_LIMIT_SECONDS
    while True:
        try:
            if os.path.isfile(SETTINGS_FILE):
                with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
                    s = json.load(f)
                if "default_cooldown" in s:
                    DEFAULT_RATE_LIMIT_SECONDS = int(s["default_cooldown"])
                if "react_enabled_global" in s and not s["react_enabled_global"]:
                    # owner switched reactions off for ALL their groups at once
                    for chat in data.values():
                        chat["react_enabled"] = False
                    save_data()
        except Exception as e:
            log.warning(f"settings_watcher error: {e}")
        await asyncio.sleep(20)


# ────────────────────────────────────────────────
#   START
# ────────────────────────────────────────────────
async def login_only():
    """Runs Telethon's normal interactive phone/OTP prompt directly in THIS
    terminal — never through a bot chat — then saves the session and exits."""
    await bot.start()
    _save_string_session(bot.session.save())
    me = await bot.get_me()
    print(f"✅ Login successful — logged in as {me.first_name} (@{me.username}).")
    print("Session saved. You can now let the factory bot start this clone,")
    print("or run this script again without --login-only to run it directly.")
    await bot.disconnect()


async def main():
    await bot.start()
    # persist the session string so future runs reuse this login instead of
    # asking for phone/OTP again — safe to call every start, it's a no-op
    # rewrite if nothing changed
    _save_string_session(bot.session.save())
    me = await bot.get_me()
    log.info("━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    log.info("🤖 FUN BOT v2.4 STARTED")
    log.info(f"👤 Logged in as → {me.first_name} (@{me.username})")
    log.info(f"🆔 User ID → {me.id}")
    log.info("━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    asyncio.create_task(settings_watcher())
    await bot.run_until_disconnected()


if __name__ == "__main__":
    if ARGS.login_only:
        asyncio.run(login_only())
    else:
        asyncio.run(main())
