```python
# ────────────────────────────────────────────────
#   OPT-IN GROUP FUN BOT v2.4 (Telethon Userbot)
#   Text replies remain opt-in/consent-based. Reactions
#   in groups are NOT consent-gated (see v2.4 note below) —
#   this raises automation-detection / ban risk, use with care.
#
#   CHANGES IN v2.4:
#   - Group reactions ab SABHI messages pe chalti hain, opt-in
#     ki zaroorat nahi (pehle sirf opted-in members ke messages
#     pe reaction milti thi). Text-reply abhi bhi sirf opted-in
#     members ke liye hai — sirf reaction ka scope badla hai.
#   - Reaction ka apna alag per-user cooldown hai (chat ke
#     `.funcooldown` wahi cooldown reuse karta hai) taaki har
#     single message pe reaction dene se flood/ban risk na badhe.
#   - `.funreact on/off` ab is naye "react-to-everyone" behaviour
#     ko bhi control karta hai.
#
#   CHANGES IN v2.3:
#   - Bot ab HAR reply pe TEXT + REAL Telegram REACTION
#     dono ek saath deta hai — group aur DM, dono jagah,
#     hamesha (pehle wala 25% random "bonus" hata diya)
#   - Reaction ab asli Telegram reaction hai (SendReactionRequest
#     se), pehle wo sirf ek extra text message tha jo dikhta
#     reaction jaisa tha lekin actually reaction nahi tha
#   - `.funreact on/off` command ab kaam karta hai (pehle sirf
#     changelog me likha tha, code me implement nahi tha)
#   - DMs me reactions hamesha allowed hain (jaisa comment me
#     pehle se likha tha)
#
#   CHANGES IN v2.2:
#   - Bot ab HAR baar TEXT reply + emoji REACTION dono
#     ek saath deta hai — group aur DM, dono jagah
#   - New admin command `.funreact on/off` to toggle
#     reactions per group (DMs always allowed to react)
#
#   CHANGES IN v2.1:
#   - All auto-replies trimmed to 2-4 words (short & punchy)
#   - Fixed opt-out bug: leaving now saves the member's
#     history to an audit log BEFORE deleting the active
#     record, instead of losing it
#   - Everything else from v2 kept (cooldowns, quiet hours,
#     triggers, moods, broadcast, export, kill-switch, etc.)
#
#   NOTE: This is a userbot (runs on a personal account via
#   Telethon), not a Bot API bot. Automating a personal
#   Telegram account like this can conflict with Telegram's
#   Terms of Service (which restrict bulk/automated messaging
#   from user accounts) and can get the account limited or
#   banned, regardless of how consent-based the feature is.
#   Worth keeping in mind before running this on a real account.
# ────────────────────────────────────────────────

import argparse
import asyncio
import json
import logging
import os
import random
import re
import sys
import time
from datetime import datetime, time as dtime
from pathlib import Path
from typing import Dict, List, Optional

from telethon import TelegramClient, events
from telethon.errors import FloodWaitError, RPCError
from telethon.sessions import StringSession
from telethon.tl.functions.messages import SendReactionRequest
from telethon.tl.types import ReactionEmoji

# ────────────────────────────────────────────────
#   CONFIG — loaded from a per-clone JSON file, NOT hardcoded.
#   Run with: python funbot_core.py --config /path/to/config.json
#   The config.json is generated by factory_bot.py and looks like:
#   {
#     "api_id": 12345678,
#     "api_hash": "...",
#     "owner_id": 123456789,
#     "session_file": "/path/to/funbot_session.txt",
#     "data_file": "/path/to/funbot_data.json"
#   }
#
#   --login-only : connects, runs Telethon's normal interactive phone/OTP
#   prompt directly in THIS terminal (never through any bot chat), saves
#   the resulting session string, then exits without starting the event
#   handlers. Use this once per clone to complete login yourself.
# ────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Fun Bot clone (per-user config)")
parser.add_argument("--config", required=True, help="Path to this clone's config.json")
parser.add_argument("--login-only", action="store_true",
                     help="Only perform interactive login and save the session, then exit")
ARGS = parser.parse_args()

CONFIG_PATH = Path(ARGS.config).resolve()
if not CONFIG_PATH.is_file():
    print(f"❌ Config file not found: {CONFIG_PATH}")
    sys.exit(1)

with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    _cfg = json.load(f)

API_ID = int(_cfg["api_id"])
API_HASH = str(_cfg["api_hash"])
OWNER_ID = int(_cfg["owner_id"])
SESSION_FILE = _cfg.get("session_file", str(CONFIG_PATH.parent / "funbot_session.txt"))
DATA_FILE = _cfg.get("data_file", str(CONFIG_PATH.parent / "funbot_data.json"))
SETTINGS_FILE = _cfg.get("settings_file", str(CONFIG_PATH.parent / "settings.json"))
LOG_FILE = _cfg.get("log_file", str(CONFIG_PATH.parent / "funbot.log"))

# Optional MongoDB sync (feature 9) — set by factory_bot.py in config.json.
# If empty, this clone just uses the local SESSION_FILE, same as before.
MONGODB_URI = _cfg.get("mongodb_uri", "")
MONGODB_DB_NAME = _cfg.get("mongodb_db_name", "funbot_factory")
MONGO_OWNER_KEY = _cfg.get("factory_owner_telegram_id", OWNER_ID)

DEFAULT_RATE_LIMIT_SECONDS = 3       # default min gap between fun-replies to same user
DM_RATE_LIMIT_SECONDS = 3            # min gap between auto-replies to same DM sender

# ────────────────────────────────────────────────
#   LOGGING
# ────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    handlers=[logging.FileHandler(LOG_FILE, encoding="utf-8"), logging.StreamHandler()],
)
log = logging.getLogger("funbot")

# ────────────────────────────────────────────────
#   REPLY BANKS (mood-based, all replies 2-4 words)
# ────────────────────────────────────────────────
HYPE_REPLIES = [
    # ── Upgraded Original Hype Messages ──
    "🔥 Full energy active bhai! Atmosphere bilkul next-level hype ho chuka hai! 🚀",
    "🎉 Party mode FULL ON! Scene set hai, ab bas non-stop chill vibes chalne do! 🥳✨",
    "🥳 Unstoppable vibes right now! Har jagah bas lit atmosphere faila hua hai! 🎆",
    "💯 Pure facts bol diye bhai! Isse behtar aur accurate statement ho hi nahi sakta! 🎯",
    "🚀 Rocket speed se upar hi upar! Agla stop seedha outer space hone wala hai! 💥",
    "⚡ Full power generation mode! Energy meter completely break ho gaya hai boss! 🔋",
    "🏆 Absolute champion move! Masterclass performance dikha diya aaj toh tumne! 🥇",
    "🎯 Direct hit on target! Perfect precision aur top-tier energy hai bhai! 🏹",
    "🎊 Grand celebration time! System me confetti aur fireworks full-on active! 🎆✨",
    "🌟 Star player alert! Main spotlight abhi seedha aapke upar focused hai! 📸",
    "🔊 Max volume baseline drop! Speaker full boost par set kar diye hain! 🎶",
    "🥇 Gold medal standard reply! Premium quality swag bilkul unmatched hai! 👑",
    "🕺 Unmatched moves & groove! Chat me dhoom mach gayi hai poori tarah se! 💃",
    "🎆 Sky-high fireworks display! Aasmaan me bas glowing celebration chal raha hai! ✨",
    "🚨 Dangerously high swag alert! Limit se bahar waali electric energy hai bhai! 🔥",
    "💣 BOOM! Explosive response delivered! Content aisa ki baaki sab dekhte reh gaye! 💥",
    "👑 King size energy check! Full domination mode turn on ho chuka hai, stay tuned! ⚡",
    "🏎️ Top gear hyper-drive mode! Speed, power aur hype sab ek saath unlock ho gaya! 🏁",
    "💎 Pure diamond-grade response! Standard itna high hai ki koi match hi nahi kar sakta! ✨",
    "🍿 Peak entertainment active! Scene me abhi aur bhi jabardast twists aayenge! 🎬",
    "🌟 Legendary presence detected! History create karne waali energy radiate ho rahi hai! 🏆",
    "🌊 Hype tsunami incoming! Is level ki energy ko handle karna next to impossible hai! ⚡",
    "🧠 Next-level genius move! Big brain gameplay dekh kar sab ke sab stunned reh gaye! 💥",
    "🔥 Ultra-instinct hype unlocked! Boundary se bahar jaakar swag spread ho raha hai! 🚀",
    "⚡ High-voltage system overload! Current itna teez hai ki meter crash ho gaya bhai! 🔌",
    "🎯 Pitch-perfect execution! Zero delay, zero error, 100% pure high-impact response! 💯",
    "🌟 Next generation trendsetter! Game ka poora format hi change kar diya aapne! 📈"
]

CHILL_REPLIES = [
    # ── Upgraded Original Chill Messages ──
    "😂 Hahahahaha wah bhai! Solid sense of humor, poora scene hi light aur joyful kar diya! ⚡",
    "🤝 Squad approved message! Poore group ka stamp lag gaya hai is relaxed vibe par! ✨",
    "😎 Cool, cool, cool, smooth response! Bilkul effortless level ka chill aura hai bhai! 🧊",
    "😅 Ye baat toh pure dil se sunni aur feel karni hi padegi! Pure positive frequency! 🕊️",
    "🙂 Sahi chal raha hai sab kuch bhai! Pure peaceful aur balanced energy spread ho rahi hai! 🍃",
    "☕ Chai pe charcha mode active! Aaram se baith ke har ek baat detailed discuss karenge! 🛋️",
    "🌤️ Ekdum halka phulka aur soothing vibe! Mind completely fresh aur relaxed ho gaya! 🌸",
    "🧘 Utmost shaant aur sukoon wali state! Sab stress door aur aura completely relaxed hai! ✨",
    "🍃 Aaram se tension free raho bhai! Koi jaldi nahi hai, smooth flow chalne do! 🕊️",
    "😌 Bilkul theek aur genuine laga padhke! Perfect harmony aur calm response! 💯",
    "🎈 Simple, sweet, solid aur zero complexity! Yehi toh asli quality hai bhai! ✨",
    "🪁 Aasmaan me udta hua light mood! Completely free-flowing aur positive mindset! 🌈",
    "🛋️ Comfy vibes only allowed here! Pillow, snacks aur chill conversations ka combo! 🍿",
    "🌙 Chill raho tension free bhai! Raat ho ya din, apan hamesha smooth mode me hain! ☕",
    "😊 Heartwarming response! Padhke sach me accha aur completely satisfying laga! ✨",
    "🌊 Deep ocean calmness level! Chill frequency match ho gayi hai poori tarah se! 🏝️",
    "🧘 Perfect state of equilibrium! Zero rush, zero noise, pure inner peace energy! ✨",
    "🍃 Gentle breeze wala peaceful atmosphere! Scene bilkul sorted aur effortless lag raha hai! 🕊️",
    "☕ Warm cup of tea aur relaxing conversations! Din set karne wala soothing response hai! 🌤️",
    "🛋️ Ultimate comfort zone unlocked! Stress zero percent, chill vibes hundred percent! 🍿",
    "🕊️ Soft aur graceful energy overall! Sab kuch ekdum systematic aur relaxed pace par hai! ✨",
    "🌟 Effortlessly cool statement! Bilkul smooth, subtle aur high-class positivity! 🪞",
    "📻 Retro chill radio vibes active! Atmosphere me ek alag hi relaxing rhythm chal rahi hai! 🎶",
    "🍀 Positivity aur good fortune spread ho raha hai! Har word me ek calming touch hai! ✨",
    "🌄 Fresh morning sunrise jaisi bright aur soothing feel! Whole day sorted by this vibe! 🌤️",
    "🍦 Ice-cool mental composure! Koi hyper noise nahi, bas pure relaxed state of mind! 🧊",
    "🕊️ Harmony, peace aur balance ka accurate blend! Perfect response to keep things cool! 🍃"
]

ROAST_REPLIES = [
    # ── Upgraded Original Roast Messages (For Normal Group Roasts) ──
    "😏 Wah kya baat hai bhai! Aisa logic toh dhoondne par bhi Google par nahi milega! 🏅",
    "🙃 Ye bhi koi baat hui bhala? Aisa lag raha hai bina brain reboot kiye type kar diya! 🧠",
    "😬 Thoda aur try karo bhai, shayad agli baar response me thoda sense aur logic aa jaaye! 🎯",
    "🤨 Substantially interesting take bhai! Aisa unique out-of-the-box thought process kahan se laaye? 🎭",
    "😂 Bhai tu bhi na, next level comedy talent chhupa ke baitha hai, Oscar milega tujhe! 🎬",
    "🫣 Path seedha toh bilkul nahi tha, kafi ghuma-phirake roundabout reasoning di hai! 🌀",
    "😜 Chal maan liya teri baat, par agli baar aisa risk lene se pehle double check kar lena! ⚠️",
    "🥲 Kabhi kabhi hota hai aisa mind-space, koi nahi hota rehta hai, improve kar loge! 🩹",
    "😅 Full drama aur cinematic exaggeration chal raha hai! Daily soap ka script likh rahe ho kya? 📺",
    "🤡 Full circus comedy energy active! Performance top-notch tha, bas logic gayab tha! 🎪",
    "🙈 Poora public square dekh raha hai ye message, thoda toh composure maintain kar lo bhai! 📢",
    "😹 Bas bas yaar aur mat hansao, pet me dard hone laga hai is unmatched creativity se! 🍿",
    "🫡 Salute hai tumhare is absolute unshakeable confidence ko! Logic zero, confidence 100%! 🚀",
    "😌 Chalta hai yaar, har din brain optimal efficiency par kaam nahi karta, take it easy! 🛋️",
    "🎭 Is response par toh multi-season Netflix drama series ban sakti hai, screenplay tayar hai! 🎬",
    "🤡 Clown university se topper log aate hain aise out-of-world statements dene ke liye! 🎪",
    "🚀 Is comment ka logic rocket se bhi tez speed me mere head ke upar se nikal gaya! 🛰️",
    "📉 Stock market ki tarah aapka logical value is message ke baad sudden crash ho gaya! 📊",
    "🧠 System searching for valid argument... Error 404: Logic not found anywhere in memory! 🔍",
    "🏆 Achievement unlocked: Masterclass in creating pure unadulterated hilarious confusion! 🎭",
    "🔎 Magnifying glass laga kar dhoond raha hoon ki is baat ka real context kahan chhupha hai! 🕵️",
    "🎪 Circus open house announcement! Aaj ka main attraction aapka ye epic response tha! 🎟️",
    "📉 Confidence level peak standard, Knowledge depth flat zero level! Dangerous combo bhai! ⚡",
    "🧙 Aise unexpected twists toh Harry Potter ki books me bhi nahi mile the bhai! 🪄",
    "📸 Picture-perfect moment of self-destruction! Internet archive me save hone layak scene hai! 💾",
    "🏅 Gold medal in jumping to wildest assumptions! Olympic panel impressed ho gaya! 🏃",
    "🎬 Mic drop moment tha, par unfortunately mic ulta pakda hua tha aapne! 🎤"
]

# 🔥 55+ NEW SPAM ROAST REPLIES (Specifically for .roast on loop) 🔥
SPAM_ROAST_REPLIES = [
    "Aur bhai, kya haal hai? Chup kyu ho gaya? 😂",
    "Bolna bhai, awaaz nahi aa rahi teri! 🎤",
    "Lagta hai darr gaya... 🏃‍♂️",
    "Bhai thoda toh bol le, kitna sharmaega? 🙈",
    "Keyboard kharab ho gaya kya tera? ⌨️",
    "Bade jaldi thak gaye yaar tum... 😴",
    "Hello? Koi hai? Ya main akele hi bol raha hu? 🗣️",
    "Dekh bhai, jab tak main off nahi karunga, ye chalta rahega! 🔥",
    "Type karne me ungliyan dard kar rahi hain kya? 🤌",
    "So gaya kya bhai itni jaldi? 🥱",
    "Net khatam ho gaya lagta hai iska! 📶",
    "Mummy ne phone chheen liya kya? 📱",
    "Bhai ki bolti band ho chuki hai! 🤐",
    "Reply karne ka tax nahi lagta, bol le thoda! 💸",
    "Arre bhai, rona nahi hai, text karna hai! 😭",
    "Lagta hai Google par reply search kar raha hai. 🔍",
    "Bhai ka system hang ho gaya hai doston! 💻",
    "Itni shaanti toh library me bhi nahi hoti. 📚",
    "Ab kya kabootar se chitthi bhejega? 🕊️",
    "Wifi ka bill kaun bharega tera? 🧾",
    "Aisa sannaata kyu hai bhai? 🤫",
    "Zinda ho ya nikal liye? 👻",
    "Are kuch toh bol mere bhai, suspense kyu bana raha hai? 🍿",
    "Bhai teri typing speed dekh ke snail ko bhi sharam aa jaye. 🐌",
    "Ghabra mat, main kuch nahi karunga... sirf spam karunga! 😈",
    "Akele akele chup baithna achhi baat nahi hai. 🙅‍♂️",
    "Chalo 10 minute ka maun vrat rakha hai bhai ne. 🧘‍♂️",
    "Are are, itna gussa ki reply hi nahi karoge? 😠",
    "Batao batao, main sun raha hu. 👂",
    "Kya soch raha hai itna? Einstein banega kya? 🧠",
    "Bhai tera sabun slow hai kya? 🧼",
    "Oye hello! Yahan dhyaan do thoda. 👋",
    "Lagta hai dost ko meri baatein pasand nahi aa rahi. 💔",
    "Abhi bhi time hai, surrender kar de! 🏳️",
    "Isse fast toh kachhua chalta hai. 🐢",
    "Lagta hai iska internet explorer 2G pe chal raha hai. 🌐",
    "O bhai saahab! Kahan kho gaye? 🔭",
    "Teri khamoshi sab kuch bayaan kar rahi hai. 🎭",
    "Koi ambulance bulao, iske keyboard ki saansein atak gayi hain! 🚑",
    "Beta tumse na ho paayega. 😂",
    "Lagta hai sadme me chala gaya bechara. 😵‍💫",
    "Bhai tu text kar raha hai ya khet jot raha hai? Itna time? 🚜",
    "Teri himmat kaise hui mujhe ignore karne ki? 😤",
    "Jawab do janta jawab chahti hai! 🎤",
    "Main rukunga nahi, chahe tu ro de aaj! 🎢",
    "Keyboard pe so gaya kya apna sar rakh ke? 💤",
    "Bhai agar zinda hai toh haath utha de bas. 🙋‍♂️",
    "Tu bas dekhta reh ab meri speed! 🚀",
    "Kahan se late ho itna patience chup rehne ka? 🗿",
    "Chalo bhai, aaj ka tera kota khatam. 🔚",
    "Thoda paani-waani pee le, thak gaya hoga chup reh ke. 🚰",
    "Main yahan bore ho raha hu, kuch toh entertain kar! 🎪",
    "Error 404: Jawab not found! ⚠️",
    "Lagta hai battery 1% pe aa gayi hai iski. 🔋",
    "Arre naraz ho kya dost? Aise ignore toh na karo! 🥺",
    "Jaldi bol subah Panvel nikalna hai! 🏃‍♂️💨"
]


NEUTRAL_REPLIES = [
    # ── Upgraded Original Neutral Messages ──
    "👍 Message officially noted aur system database me successfully log kar diya gaya hai! 📝",
    "✅ Bilkul theek hai bhai, points acknowledged aur process ke liye queue me add kar diye hain! 📌",
    "🙌 Squad operational approval confirmed! Message successfully reviewed by the team! 📋",
    "🤗 Accha laga input padhke, accurate positioning ke sath information transfer ho gayi! 💡",
    "💬 Baat toh valid aur accurate hai, structured manner me points presenting acchi hai! 📊",
    "📌 Important highlight points register kar liye gaye hain, reference ke liye save rahenge! 📁",
    "🎶 Is frequency aur rhythm par focus bana ke rakho, systematic execution dikh rahi hai! ⚙️",
    "🧩 Poora puzzle piece bilkul accurately fit baith gaya hai! Everything aligns properly! 🎯",
    "📊 Data successfully received aur process ho gaya! Standard protocol flow continue ho raha hai! 📑",
    "📥 Input successfully logged in the central repository! Next steps pipeline me align hain! ⏳",
    "🧠 Thoughtful structure aur systematic delivery! Communication standard maintain rakha gaya hai! 🖊️",
    "📌 Strategic note recorded! Continuous coordination aur balance ke sath आगे badhenge! 🎯",
    "📝 Documentation updated as per the latest input! Clear, direct aur relevant details hain! 🗂️",
    "📐 Standard measurement ke acche alignment me hai statement! Perfectly balanced perspective! 🔍",
    "🛰️ Communication signal loud aur clear receive hua! System ready for next action steps! 📡",
    "⚖️ Objective perspective successfully delivered! Fair, balanced aur precise message format! 📜",
    "🗃️ Entry successfully archived for future reference! Everything operates as expected! ⚙️",
    "💡 Valid information exchange detected! Context completely clear aur well organized hai! 🔍",
    "🤝 Mutual alignment achieved on this point! Progressing further in a structured order! 📈",
    "📈 Baseline information registered! Communication flow smooth aur effective bana hua hai! 🎯"
]


MOOD_BANKS = {
    "hype": HYPE_REPLIES,
    "chill": CHILL_REPLIES,
    "roast": ROAST_REPLIES,
}

ALL_REPLIES = HYPE_REPLIES + CHILL_REPLIES + ROAST_REPLIES + NEUTRAL_REPLIES

DM_REPLIES = [
    # ── Upgraded Original Away/Busy Messages ──
    "👋 Hey! Abhi thoda busy hoon ek important task me. Jaise hi free hota hoon, aapko proper reply karta hoon! ⏳",
    "😊 Message mil gaya hai! Currently main unavailable hoon, thodi der me free ho kar aap se baat karta hoon. ✨",
    "🙌 Aapka message process ho gaya hai. Abhi thoda time lag sakta hai, par jald hi detailed response bhejunga! 📩",
    "📩 Notification receive ho gayi hai! System se active hotey hi aapko turant text back karta hoon. 📌",
    "⏳ Abhi thoda away hoon desktop/mobile se. Wapas aate hi sabse pehle aapke message ka answer dunga! 🏃‍♂️",
    "🙏 Aapka patience appreciated hai! Main abhi ek work session me hoon, free hotey hi connect karta hoon. 💯",
    "🕐 Thoda wait kar lijiye please, main message read kar chuka hoon aur jald hi aap se interact karunga! 🤝",
    "📨 Message securely receive ho gaya hai. Thodi der me clear aur proper solution/reply ke sath aata hoon! ✍️",
    "😴 Abhi offline/away mode active hai. Wapas active hotey hi aapko notification chala jayega! 🌙",
    "🚶 Out of station / task me busy hoon abhi. Jald hi desktop par wapas aakar reply drop karta hoon! 💻",
    "✋ Message check kar liya hai, but abhi reply dene ka time nahi hai. Thodi der me milte hain! 🔍",
    "🔔 Ping receive ho gaya hai! Next available slot me aapko turant text message mil jayega. 📱",
    "📲 Aapka query/message log ho gaya hai. Fret not, jald hi personalized reply bhej raha hoon! 🚀",
    "🙋 Hey! Inbox me message dekha. Thoda hold rakho, full focus ke sath response bhejta hoon! ⚡",
    "🧘 Quiet mode on hai abhi. Jald hi active hokar aap se detailed discussion karta hoon! 🕊️",
    # ── 10+ New Detailed & Professional Away Messages ──
    "📊 Currently high-priority tasks handle kar raha hoon. Important updates ke sath jald hi inbox me milta hoon! 🎯",
    "📌 Aapka DM inbox me safe hai! Schedule break milte milte hi aapko prioritized response bhej dunga. 📋",
    "💻 Active execution mode ongoing! Task wrap-up karte hi aapko detailed answer ke sath DM karta hoon! ⚡",
    "⚙️ Auto-responder status: Main abhi system se away hoon, but don't worry, aapka text note kar liya gaya hai! 📥",
    "🚀 High efficiency mode me hoon abhi! Jald hi screen par wapas aakar aapse properly connect karta hoon! 🌐",
    "🛡️ Priority session me busy hone ki wajah se delay ke liye sorry. Jald hi aapke DM ka response aayega! ⌛",
    "📑 Message queued successfully! Jaise hi current workflow complete hota hai, aapko reach out karta hoon! 📬",
    "🎯 Focused work mode ongoing. Interruptions avoid karne ke liye baad me reply dunga, thanks for understanding! 🧠",
    "🔔 Alert set kar diya hai aapke DM par! Jaise hi notifications review karta hoon, aapko ping karunga! 📶",
    "💡 Query/Message receive ho gaya hai! Proper research/analysis ke sath detailed response bhejunga! 📝",
    "🏁 Workflow finish hone wala hai. Bus 10-15 mins me aapse chat par connect hota hoon! ⏱️",
    "✨ Thanks for reaching out! Main filhaal away hoon par aapka topic prioritize kar ke jald reply dunga! 🌟",
]

# ── Keyword → Context-Aware DM Reply Banks (Detailed & Professional) ──
DM_GREETING_TRIGGERS = [
    "hi", "hii", "hiii", "hello", "hey", "namaste", "namaskar", "yo",
]
DM_GREETING_REPLIES = [
    "👋 Hey! Warm welcome to the chat. Aashayein hain sab accha chal raha hoga, bataiye kaise madad kar sakta hoon? ✨",
    "😊 Hello! Bohot accha laga aapse connect karke. Kaise hain aap aur aaj ka din kaisa chal raha hai? 🌟",
    "🙌 Hii there! Sab kuch perfectly fine hai yahan. Aap bataiye, aaj inbox me aane ka kya main reason hai? 💬",
    "😄 Hey! Super glad to see your message today. Bataiye kya new updates hain aur kaise chal raha hai sab? 🚀",
]

DM_HOWAREYOU_TRIGGERS = [
    "how are you", "kaise ho", "kaisi ho", "kya haal", "kya hal", "sab theek",
]
DM_HOWAREYOU_REPLIES = [
    "😊 Main bilkul badhiya aur healthy hoon! Aap bataiye, aapke wahan sab kaisa chal raha hai? 🍃",
    "🙌 Poori tarah se set aur functional hoon! System aur mood dono high output par hain, aap sunao? ⚡",
    "😎 Ekdum mast aur energetic vibe me hoon bhai! Life full smooth track par hai, aapka kya haal chaal? 🚀",
]

DM_THANKS_TRIGGERS = [
    "thanks", "thank you", "thnx", "tysm", "shukriya", "dhanyawad",
]
DM_THANKS_REPLIES = [
    "🙏 Absolutely zero problem bhai! Madad karke bohot khushi hui, kisi bhi waqt bejhijhak text kar sakte ho! ✨",
    "😊 Most welcome brother! Aapka appreciation read karke accha laga. Hamesha aapki help ke liye ready hoon! 🌟",
    "🤝 Anytime my friend! Mutual support hi toh sabse important hai. Jab bhi zaroorat ho, ping kar dena! 💯",
]

DM_BYE_TRIGGERS = [
    "bye", "gtg", "good night", "goodnight", "chalta hoon", "milte hai", "milte hain", "tata",
]
DM_BYE_REPLIES = [
    "👋 Good bye aur apna poora dhyan rakhna! Phir milte hain ek naye conversation ke sath. Take care! ✨",
    "😴 Peaceful Good Night! Raat ko acchi aur sukoon bhari neend aaye aapko, kal subah naye energy se milte hain! 🌙",
    "🙌 Catch you later! Baad me fursat se milte aur baat karte hain, tab tak apna work continue rakho! 🚀",
]

DM_QUESTION_TRIGGERS = ["?", "kya", "kaise", "kyu", "kyun", "kab", "kahan", "kaun"]
DM_QUESTION_REPLIES = [
    "🤔 Bohot hi genuine aur thought-provoking sawal hai! Main is par deep detail ke sath jald reply bhejta hoon. 📝",
    "📝 Question receive ho gaya hai! Main is topic par accurate details check karke clear answer text karta hoon. 📌",
    "🧐 Deeply analysis worthy question! Thoda time do, bilkul precise aur correct information batata hoon. 📊",
]

DM_LOVE_TRIGGERS = ["love you", "miss you", "pyaar", "ilu"]
DM_LOVE_REPLIES = [
    "🥰 Aww, that's incredibly sweet and heart-warming! Aapki kindness aur love read karke bohot accha laga! ❤️",
    "❤️ Pure respect aur genuine affection ke sath thanks! Aapka ye wholesome support mere liye bohot mean karta hai! ✨",
    "🤗 Right back at you my friend! True bonding aur mutual respect hamesha maintain rahegi hamari! 💯",
]

DM_ANGRY_TRIGGERS = ["gussa", "angry", "naraz", "irritat", "pareshan"]
DM_ANGRY_REPLIES = [
    "😟 Sab theek hai na? Please tension mat lo, aaram se batayiye kya issue hua hai jisse pareshani hui? 🫂",
    "🫂 Calm aura aur deep breath lo my friend. Gussa hone se situation clear nahi hoti, milkar solve karte hain! ✨",
    "💬 Main poori tarah se tayar hoon sunne ke liye. Clear tarike se batao kya baat hui hai, issue resolve karenge! 📌",
]


# Ordered so more specific/emotional intents are checked before generic ones
DM_INTENT_BANKS = [
    (DM_ANGRY_TRIGGERS, DM_ANGRY_REPLIES),
    (DM_LOVE_TRIGGERS, DM_LOVE_REPLIES),
    (DM_THANKS_TRIGGERS, DM_THANKS_REPLIES),
    (DM_BYE_TRIGGERS, DM_BYE_REPLIES),
    (DM_HOWAREYOU_TRIGGERS, DM_HOWAREYOU_REPLIES),
    (DM_GREETING_TRIGGERS, DM_GREETING_REPLIES),
    (DM_QUESTION_TRIGGERS, DM_QUESTION_REPLIES),
]


def _trigger_matches(text_lower: str, words: set, trigger: str) -> bool:
    if trigger == "?":
        return "?" in text_lower
    if " " in trigger:
        return trigger in textlower
    return trigger in words


def pick_dm_reply(uid: int, text: str) -> str:
    lowered = (text or "").lower()
    words = set(re.findall(r"[a-z]+", lowered))

    bank = DM_REPLIES
    for triggers, replies in DM_INTENT_BANKS:
        if any(_trigger_matches(lowered, words, t) for t in triggers):
            bank = replies
            break

    reply = random.choice(bank)
    tries = 0
    while reply == last_dm_reply_text.get(uid) and tries < 5 and len(bank) > 1:
        reply = random.choice(bank)
        tries += 1
    last_dm_reply_text[uid] = reply
    return reply

REACTION_EMOJIS = ["👍", "🔥", "😂", "❤️", "🎉", "👏", "😎", "💯"]

# ────────────────────────────────────────────────
#   STORAGE & STATE
# ────────────────────────────────────────────────
data: Dict[str, dict] = {}
last_reply_time: Dict[int, float] = {}
last_dm_reply_time: Dict[int, float] = {}
last_reply_text: Dict[int, str] = {}   # avoid immediate repeats per user (groups)
last_dm_reply_text: Dict[int, str] = {}  # avoid immediate repeats per user (DMs)
last_react_time: Dict[tuple, float] = {}  # (chat_id, user_id) -> ts, flood-protection
REACTION_ALL_COOLDOWN_SECONDS = 3
bot_alive = True                        # global kill-switch state

# 🔥 NEW: Store active roast spam loops 🔥
active_roasts: Dict[int, asyncio.Task] = {}


def load_data():
    global data
    try:
        if os.path.isfile(DATA_FILE):
            with open(DATA_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
        else:
            data = {}
    except Exception as e:
        log.error(f"Load error: {e}")
        data = {}


def save_data():
    try:
        with open(DATA_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        log.error(f"Save error: {e}")


def get_chat(chat_id: int) -> dict:
    key = str(chat_id)
    if key not in data:
        data[key] = {
            "enabled": False,
            "cooldown": DEFAULT_RATE_LIMIT_SECONDS,
            "quiet_start": None,
            "quiet_end": None,
            "triggers": {},
            "members": {},
            "audit": [],
            "react_enabled": True,
        }
    chat = data[key]
    chat.setdefault("cooldown", DEFAULT_RATE_LIMIT_SECONDS)
    chat.setdefault("quiet_start", None)
    chat.setdefault("quiet_end", None)
    chat.setdefault("triggers", {})
    chat.setdefault("members", {})
    chat.setdefault("audit", [])
    chat.setdefault("react_enabled", True)
    return chat


load_data()

def _load_string_session() -> str:
    if os.path.isfile(SESSION_FILE):
        try:
            with open(SESSION_FILE, "r", encoding="utf-8") as f:
                return f.read().strip()
        except Exception as e:
            log.error(f"Could not read {SESSION_FILE}: {e}")
    return ""


def _save_string_session(session_str: str):
    try:
        with open(SESSION_FILE, "w", encoding="utf-8") as f:
            f.write(session_str)
        os.chmod(SESSION_FILE, 0o600)
    except Exception as e:
        log.error(f"Could not save {SESSION_FILE}: {e}")

    if MONGODB_URI:
        try:
            from pymongo import MongoClient
            client = MongoClient(MONGODB_URI, serverSelectionTimeoutMS=5000)
            client[MONGODB_DB_NAME]["clones"].update_one(
                {"owner_id": MONGO_OWNER_KEY},
                {"$set": {"session_string": session_str}},
                upsert=True,
            )
            client.close()
            log.info("Session string synced to MongoDB.")
        except Exception as e:
            log.warning(f"MongoDB session sync failed (non-fatal, local file still saved): {e}")


bot = TelegramClient(StringSession(_load_string_session()), API_ID, API_HASH, auto_reconnect=True)


async def is_group_admin(event) -> bool:
    if event.sender_id == OWNER_ID:
        return True
    try:
        perms = await bot.get_permissions(event.chat_id, event.sender_id)
        return bool(perms.is_admin or perms.is_creator)
    except Exception:
        return False


HUMAN_MODE = False
SLEEP_START = "00:00"
SLEEP_END = "06:00"
HUMAN_MIN_DELAY = 1.0
HUMAN_MAX_DELAY = 3.5


def is_sleeping() -> bool:
    if not HUMAN_MODE:
        return False
    try:
        now = datetime.now().time()
        start = dtime.fromisoformat(SLEEP_START)
        end = dtime.fromisoformat(SLEEP_END)
        if start <= end:
            return start <= now <= end
        return now >= start or now <= end
    except Exception:
        return False


async def human_delay():
    if HUMAN_MODE:
        await asyncio.sleep(random.uniform(HUMAN_MIN_DELAY, HUMAN_MAX_DELAY))


def in_quiet_hours(chat: dict) -> bool:
    start_s, end_s = chat.get("quiet_start"), chat.get("quiet_end")
    if not start_s or not end_s:
        return False
    try:
        now = datetime.now().time()
        start = dtime.fromisoformat(start_s)
        end = dtime.fromisoformat(end_s)
        if start <= end:
            return start <= now <= end
        return now >= start or now <= end
    except Exception:
        return False


def pick_reply(uid: int, mood: str) -> str:
    bank = MOOD_BANKS.get(mood, ALL_REPLIES)
    reply = random.choice(bank)
    tries = 0
    while reply == last_reply_text.get(uid) and tries < 5 and len(bank) > 1:
        reply = random.choice(bank)
        tries += 1
    last_reply_text[uid] = reply
    return reply


def parse_hhmm(s: str) -> Optional[str]:
    try:
        h, m = s.split(":")
        h, m = int(h), int(m)
        if 0 <= h <= 23 and 0 <= m <= 59:
            return f"{h:02d}:{m:02d}"
    except Exception:
        pass
    return None


async def send_real_reaction(chat_id: int, msg_id: int, emoji: Optional[str] = None):
    chosen = emoji or random.choice(REACTION_EMOJIS)
    try:
        await human_delay()
        await bot(SendReactionRequest(
            peer=chat_id,
            msg_id=msg_id,
            reaction=[ReactionEmoji(emoticon=chosen)],
        ))
    except FloodWaitError as fw:
        log.warning(f"Flood wait on reaction: {fw.seconds}s")
        await asyncio.sleep(fw.seconds)
    except RPCError as e:
        log.warning(f"Reaction RPC error: {e}")
    except Exception as e:
        log.warning(f"Reaction failed: {e}")


# ────────────────────────────────────────────────
#   COMMANDS — membership
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.joinfun$"))
async def join_fun(event):
    if not event.is_group:
        return await event.reply("⚠️ Ye command sirf group me chalta hai.")
    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)
    if uid in chat["members"]:
        return await event.reply("✅ Aap already opted-in ho.")
    chat["members"][uid] = {
        "mood": "chill",
        "joined_at": datetime.now().isoformat(timespec="seconds"),
        "reply_count": 0,
    }
    save_data()
    await event.reply("🎉 Aap fun-mode me opt-in ho gaye! Bahar aane ke liye `.leavefun` bhejo.\nMood set karne ke liye: `.funtype hype|chill|roast`")


@bot.on(events.NewMessage(pattern=r"^\.leavefun$"))
async def leave_fun(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)
    member = chat["members"].get(uid)
    if not member:
        return await event.reply("ℹ️ Aap opted-in nahi the.")
    chat["audit"].append({
        "user_id": uid,
        "joined_at": member.get("joined_at"),
        "left_at": datetime.now().isoformat(timespec="seconds"),
        "reply_count": member.get("reply_count", 0),
    })
    del chat["members"][uid]
    save_data()
    await event.reply("👋 Aap fun-mode se bahar ho gaye.")


@bot.on(events.NewMessage(pattern=r"^\.funtype (hype|chill|roast)$"))
async def set_mood(event):
    if not event.is_group:
        return
    chat = get_chat(event.chat_id)
    uid = str(event.sender_id)
    if uid not in chat["members"]:
        return await event.reply("⚠️ Pehle `.joinfun` karo.")
    mood = event.pattern_match.group(1)
    chat["members"][uid]["mood"] = mood
    save_data()
    await event.reply(f"🎛️ Aapka fun-mood set ho gaya: **{mood}**")


# ────────────────────────────────────────────────
#   COMMANDS — admin controls
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.funmode (on|off)$"))
async def fun_mode_toggle(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    state = event.pattern_match.group(1) == "on"
    chat = get_chat(event.chat_id)
    chat["enabled"] = state
    save_data()
    await event.reply(f"⚙️ Fun-mode is group ke liye **{'ON' if state else 'OFF'}** kar diya gaya.")


@bot.on(events.NewMessage(pattern=r"^\.funreact (on|off)$"))
async def fun_react_toggle(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    state = event.pattern_match.group(1) == "on"
    chat = get_chat(event.chat_id)
    chat["react_enabled"] = state
    save_data()
    await event.reply(f"😀 Reactions is group ke liye **{'ON' if state else 'OFF'}** kar di gayi.")


@bot.on(events.NewMessage(pattern=r"^\.funcooldown (\d+)$"))
async def set_cooldown(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    seconds = max(5, min(int(event.pattern_match.group(1)), 3600))
    chat = get_chat(event.chat_id)
    chat["cooldown"] = seconds
    save_data()
    await event.reply(f"⏱️ Cooldown set ho gaya: **{seconds}s** per user.")


@bot.on(events.NewMessage(pattern=r"^\.funquiet (\d{1,2}:\d{2}) (\d{1,2}:\d{2})$"))
async def set_quiet_hours(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    start = parse_hhmm(event.pattern_match.group(1))
    end = parse_hhmm(event.pattern_match.group(2))
    if not start or not end: return await event.reply("⚠️ Format: `.funquiet 23:00 07:00`")
    chat = get_chat(event.chat_id)
    chat["quiet_start"] = start
    chat["quiet_end"] = end
    save_data()
    await event.reply(f"🌙 Quiet hours set: **{start} → {end}**")


@bot.on(events.NewMessage(pattern=r"^\.funquiet off$"))
async def clear_quiet_hours(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    chat = get_chat(event.chat_id)
    chat["quiet_start"], chat["quiet_end"] = None, None
    save_data()
    await event.reply("☀️ Quiet hours hata diye gaye.")


@bot.on(events.NewMessage(pattern=r"^\.trigger add (\S+) (.+)$"))
async def trigger_add(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    word = event.pattern_match.group(1).lower()
    chat = get_chat(event.chat_id)
    chat["triggers"][word] = event.pattern_match.group(2)
    save_data()
    await event.reply(f"➕ Trigger add ho gaya: `{word}`")


@bot.on(events.NewMessage(pattern=r"^\.trigger remove (\S+)$"))
async def trigger_remove(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    word = event.pattern_match.group(1).lower()
    chat = get_chat(event.chat_id)
    if word in chat["triggers"]:
        del chat["triggers"][word]
        save_data()
        await event.reply(f"➖ Trigger hata diya: `{word}`")


@bot.on(events.NewMessage(pattern=r"^\.trigger list$"))
async def trigger_list(event):
    if not event.is_group: return
    chat = get_chat(event.chat_id)
    if not chat["triggers"]: return await event.reply("ℹ️ Koi trigger set nahi hai.")
    lines = [f"• `{w}` → {r}" for w, r in chat["triggers"].items()]
    await event.reply("🧵 **Active Triggers:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funbroadcast (.+)$"))
async def fun_broadcast(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    msg = event.pattern_match.group(1)
    chat = get_chat(event.chat_id)
    if not chat["members"]: return await event.reply("ℹ️ Koi opted-in member nahi hai.")
    sent, failed = 0, 0
    for uid_str in list(chat["members"].keys()):
        try:
            await bot.send_message(int(uid_str), f"📢 **Fun Bot Announcement:**\n{msg}")
            sent += 1
            await asyncio.sleep(1)
        except Exception: failed += 1
    await event.reply(f"📨 Broadcast bhej diya. ✅ Sent: {sent} | ❌ Failed: {failed}")


@bot.on(events.NewMessage(pattern=r"^\.funkill$"))
async def fun_kill(event):
    global bot_alive
    if event.sender_id != OWNER_ID: return
    bot_alive = False
    await event.reply("🛑 Bot globally paused (owner only). `.funrevive` se wapas on karo.")


@bot.on(events.NewMessage(pattern=r"^\.funrevive$"))
async def fun_revive(event):
    global bot_alive
    if event.sender_id != OWNER_ID: return
    bot_alive = True
    await event.reply("✅ Bot wapas active ho gaya.")

# ────────────────────────────────────────────────
# 🔥 NEW FEATURE: ROAST LOOP (Auto Spam)
# ────────────────────────────────────────────────
async def roast_loop(chat_id: int):
    """Background task to send a roast message every 3 seconds."""
    try:
        while bot_alive:
            # Pura SPAM_ROAST_REPLIES me se random message chusega 
            msg = random.choice(SPAM_ROAST_REPLIES)
            await bot.send_message(chat_id, msg)
            await asyncio.sleep(3) # Har 3 second me bhejega
    except asyncio.CancelledError:
        pass # Loop ko gracefully band karne ke liye

@bot.on(events.NewMessage(pattern=r"^\.roast (on|off)$"))
async def toggle_roast_spam(event):
    """Command to start/stop the continuous roast loop in any chat."""
    # Sirf Bot Owner ye command use kar sakta hai
    if event.sender_id != OWNER_ID:
        return

    action = event.pattern_match.group(1).lower()
    chat_id = event.chat_id

    if action == "on":
        if chat_id in active_roasts:
            return await event.edit("🔥 Roast mode is chat me pehle se ON hai bhai!")
        
        await event.edit("🔥 **Roast Mode ON!** Ab dekh iska kya haal karta hoon... 🔥")
        
        # Background task create karo
        task = asyncio.create_task(roast_loop(chat_id))
        active_roasts[chat_id] = task

    elif action == "off":
        if chat_id in active_roasts:
            # Task ko cancel karo
            active_roasts[chat_id].cancel()
            del active_roasts[chat_id]
            await event.edit("🛑 **Roast Mode OFF!** Chalo maaf kiya isko.")
        else:
            await event.edit("ℹ️ Yahan koi roast chalu hi nahi tha bhai.")

# ────────────────────────────────────────────────
#   COMMANDS — info
# ────────────────────────────────────────────────
@bot.on(events.NewMessage(pattern=r"^\.funlist$"))
async def fun_list(event):
    if not event.is_group: return
    chat = get_chat(event.chat_id)
    if not chat["members"]: return await event.reply("ℹ️ Is group me abhi koi opt-in nahi hai.")
    lines = []
    for uid_str, info in chat["members"].items():
        lines.append(f"• (`{uid_str}`) — mood: {info.get('mood', 'chill')}")
    await event.reply("👥 **Opted-in members:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funstats$"))
async def fun_stats(event):
    if not event.is_group: return
    chat = get_chat(event.chat_id)
    if not chat["members"]: return await event.reply("ℹ️ Abhi koi data nahi hai.")
    ranked = sorted(chat["members"].items(), key=lambda kv: kv[1].get("reply_count", 0), reverse=True)
    lines = [f"• `{uid_str}` — {info.get('reply_count', 0)} replies" for uid_str, info in ranked[:10]]
    await event.reply("🏆 **Fun Leaderboard:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.funaudit$"))
async def fun_audit(event):
    if not event.is_group: return
    if not await is_group_admin(event): return
    chat = get_chat(event.chat_id)
    if not chat["audit"]: return await event.reply("ℹ️ Abhi koi audit record nahi hai.")
    lines = [f"• `{r['user_id']}` — {r.get('joined_at')} to {r.get('left_at')}" for r in chat["audit"][-10:]]
    await event.reply("📜 **Recent opt-out audit:**\n" + "\n".join(lines))


@bot.on(events.NewMessage(pattern=r"^\.(?:funhelp|help)$"))
async def fun_help(event):
    text = (
        "🤖 **Fun Bot v2.4 — Complete Command Reference**\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**🔥 Special Tools (DM/Group)**\n"
        "😈 `.roast on/off` — Target ko continuously har 3s me roast karo (Spam mode)\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**👤 Membership (Groups)**\n"
        "🎉 `.joinfun` — fun-mode me opt-in karo\n"
        "👋 `.leavefun` — opt-out karo\n"
        "🎛️ `.funtype hype|chill|roast` — apna reply-mood chuno\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**⚙️ Group Settings** _(admins only)_\n"
        "🔛 `.funmode on/off` — fun-mode enable/disable\n"
        "😀 `.funreact on/off` — group reactions on/off\n"
        "⏱️ `.funcooldown <seconds>` — set gap b/w replies (e.g. 5)\n"
        "🌙 `.funquiet <start> <end>` — sleep hours (e.g. 23:00 07:00)\n"
        "☀️ `.funquiet off` — quiet hours disable karo\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**🧵 Triggers (Custom Auto-Reply)**\n"
        "➕ `.trigger add <word> <reply>` — naya trigger lagao\n"
        "➖ `.trigger remove <word>` — trigger hatao\n"
        "📋 `.trigger list` — saare active triggers dekho\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**📊 Info & Logs**\n"
        "👥 `.funlist` — opted-in members ki list\n"
        "🏆 `.funstats` — sabse jyada reply paane wale log\n"
        "📜 `.funaudit` — recent opt-outs ki list\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "**👑 Owner Controls**\n"
        "📢 `.funbroadcast <msg>` — saare members ko message bhejo\n"
        "🛑 `.funkill` — bot ko globally pause karo\n"
        "✅ `.funrevive` — bot ko wapas active karo\n"
    )
    await event.reply(text)


# ────────────────────────────────────────────────
#   AUTO FUN-REPLY (opt-in + rate-limited + mood + quiet hours)
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_fun(event):
    if not bot_alive or event.out or not event.is_group or is_sleeping():
        return

    # 🔥 NEW: Agar is chat me ROAST LOOP chal raha hai, to normal reply mat karo
    if event.chat_id in active_roasts:
        return

    text = event.raw_text or ""
    if text.startswith("."):
        return

    chat = get_chat(event.chat_id)
    if not chat["enabled"] or in_quiet_hours(chat):
        return

    uid = event.sender_id
    uid_str = str(uid)
    member = chat["members"].get(uid_str)
    if not member:
        return

    lowered = text.lower()
    trigger_hit = None
    for word, reply_text in chat["triggers"].items():
        if word in lowered:
            trigger_hit = reply_text
            break

    now = time.time()
    if now - last_reply_time.get(uid, 0) < chat.get("cooldown", DEFAULT_RATE_LIMIT_SECONDS):
        return
    last_reply_time[uid] = now

    try:
        await human_delay()
        reply_text_out = trigger_hit if trigger_hit else pick_reply(uid, member.get("mood", "chill"))
        await event.reply(reply_text_out)
        member["reply_count"] = member.get("reply_count", 0) + 1
        save_data()
    except FloodWaitError as fw:
        await asyncio.sleep(fw.seconds)
    except Exception:
        pass


# ────────────────────────────────────────────────
#   AUTO REACTION — ALL GROUP MESSAGES (no opt-in required)
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_react_group(event):
    if not bot_alive or event.out or not event.is_group or is_sleeping():
        return
    text = event.raw_text or ""
    if text.startswith("."):
        return

    chat = get_chat(event.chat_id)
    if not chat["enabled"] or not chat.get("react_enabled", True) or in_quiet_hours(chat):
        return

    uid = event.sender_id
    key = (event.chat_id, uid)
    now = time.time()
    if now - last_react_time.get(key, 0) < REACTION_ALL_COOLDOWN_SECONDS:
        return
    last_react_time[key] = now

    await send_real_reaction(event.chat_id, event.id)


# ────────────────────────────────────────────────
#   AUTO DM-REPLY
# ────────────────────────────────────────────────
@bot.on(events.NewMessage)
async def auto_dm(event):
    if not bot_alive or event.out or not event.is_private or is_sleeping():
        return

    # 🔥 NEW: Agar is DM me ROAST LOOP chal raha hai, to normal reply mat karo
    if event.chat_id in active_roasts:
        return

    text = event.raw_text or ""
    if text.startswith("."):
        return

    uid = event.sender_id
    now = time.time()
    if now - last_dm_reply_time.get(uid, 0) < DM_RATE_LIMIT_SECONDS:
        return
    last_dm_reply_time[uid] = now

    try:
        reply = pick_dm_reply(uid, text)
        await event.reply(reply)
        await send_real_reaction(event.chat_id, event.id)
    except FloodWaitError as fw:
        await asyncio.sleep(fw.seconds)
    except Exception:
        pass


# ────────────────────────────────────────────────
#   SETTINGS HOT-RELOAD
# ────────────────────────────────────────────────
async def settings_watcher():
    global DEFAULT_RATE_LIMIT_SECONDS, HUMAN_MODE, SLEEP_START, SLEEP_END
    was_sleeping = False
    while True:
        try:
            if os.path.isfile(SETTINGS_FILE):
                with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
                    s = json.load(f)
                if "default_cooldown" in s:
                    DEFAULT_RATE_LIMIT_SECONDS = int(s["default_cooldown"])
                if "react_enabled_global" in s and not s["react_enabled_global"]:
                    for chat in data.values():
                        chat["react_enabled"] = False
                    save_data()
                if "human_mode" in s:
                    HUMAN_MODE = bool(s["human_mode"])
                if "sleep_start" in s:
                    SLEEP_START = s["sleep_start"]
                if "sleep_end" in s:
                    SLEEP_END = s["sleep_end"]
        except Exception:
            pass
        await asyncio.sleep(20)


# ────────────────────────────────────────────────
#   START
# ────────────────────────────────────────────────
async def login_only():
    await bot.start()
    _save_string_session(bot.session.save())
    me = await bot.get_me()
    print(f"✅ Login successful — logged in as {me.first_name} (@{me.username}).")
    await bot.disconnect()


async def main():
    await bot.start()
    _save_string_session(bot.session.save())
    me = await bot.get_me()
    log.info("🤖 FUN BOT v2.4 STARTED (With 55+ Messages Roast Loop & Full Help Menu)")
    log.info(f"👤 Logged in as → {me.first_name}")
    asyncio.create_task(settings_watcher())
    await bot.run_until_disconnected()


if __name__ == "__main__":
    if ARGS.login_only:
        asyncio.run(login_only())
    else:
        asyncio.run(main())

```
